### ISSUE TITLE
How to remap category on custom dataset?

### ISSUE THREAD

**Issue by Zailushang211** [Peterande/D-FINE#10]
Could please provide config file or guideline for training on single gpu？ the provided guideline for custom dataset training always leads to error as following, i changed the CUDA_VISIBLE_DEVICES=0, and num_workers: 0
it seems related with settings about multiple gpu, and shows long list of operator(): block: 
/opt/conda/conda-bld/pytorch_1728945388353/work/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [263,0,0], thread: [94,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1728945388353/work/aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [263,0,0], thread: [95,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/lzh/lizhihua/D-FINE/train.py", line 84, in <module>
    main(args)
  File "/home/lzh/lizhihua/D-FINE/train.py", line 54, in main
    solver.fit()
  File "/home/lzh/lizhihua/D-FINE/src/solver/det_solver.py", line 46, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/home/lzh/lizhihua/D-FINE/src/solver/det_engine.py", line 63, in train_one_epoch
    loss_dict = criterion(outputs, targets, **metas)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/lizhihua/D-FINE/src/zoo/dfine/dfine_criterion.py", line 236, in forward
    indices = self.matcher(outputs_without_aux, targets)['indices']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/lizhihua/D-FINE/src/zoo/dfine/matcher.py", line 99, in forward
    cost_bbox = torch.cdist(out_bbox, tgt_bbox, p=1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzh/miniconda3/envs/dfine/lib/python3.11/site-packages/torch/functional.py", line 1478, in cdist
    return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=

**Comment by Peterande** [comment]
> RTX3090 reproduce, total batch size 16: `torchrun train.py -c configs/dfine/dfine_hgnetv2_${model}_coco.yml --use-amp --seed=0` ![image](https://private-user-images.githubusercontent.com/52695035/378725202-d93e4fb0-12c2-41eb-b29b-b78c13f6418d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ3NTQsIm5iZiI6MTczMDI3NDQ1NCwicGF0aCI6Ii81MjY5NTAzNS8zNzg3MjUyMDItZDkzZTRmYjAtMTJjMi00MWViLWIyOWItYjc4YzEzZjY0MThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzBjMGRmY2EzYzRlMDdlOGY3ZWE1NzE5MzIxOGEyMWVlZTFkNjczMWI2YTE5YWZiOTU1MGRlZmRkNjdlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iBI692LVRz5R0Zc93w3fDDzPcBoMAtIqF-ytamxPR2I)
> 
> ```
> 
> Epoch: [0]  [   0/7392]  eta: 4:33:43  lr: 0.000000  loss: 59.3918 (59.3918)  loss_vfl: 0.3718 (0.3718)  loss_bbox: 1.5937 (1.5937)  loss_giou: 1.8046 (1.8046)  loss_fgl: 0.4020 (0.4020)  loss_vfl_aux_0: 0.4233 (0.4233)  loss_bbox_aux_0: 1.5937 (1.5937)  loss_giou_aux_0: 1.8046 (1.8046)  loss_fgl_aux_0: 0.4020 (0.4020)  loss_vfl_aux_1: 0.3875 (0.3875)  loss_bbox_aux_1: 1.5937 (1.5937)  loss_giou_aux_1: 1.8046 (1.8046)  loss_fgl_aux_1: 0.4020 (0.4020)  loss_vfl_aux_2: 0.3889 (0.3889)  loss_bbox_aux_2: 1.5937 (1.5937)  loss_giou_aux_2: 1.8046 (1.8046)  loss_fgl_aux_2: 0.4020 (0.4020)  loss_vfl_aux_3: 0.3877 (0.3877)  loss_bbox_aux_3: 1.5937 (1.5937)  loss_giou_aux_3: 1.8046 (1.8046)  loss_fgl_aux_3: 0.4020 (0.4020)  loss_vfl_aux_4: 0.3689 (0.3689)  loss_bbox_aux_4: 1.5937 (1.5937)  loss_giou_aux_4: 1.8046 (1.8046)  loss_fgl_aux_4: 0.4020 (0.4020)  loss_vfl_pre: 0.4233 (0.4233)  loss_bbox_pre: 1.5937 (1.5937)  loss_giou_pre: 1.8046 (1.8046)  loss_vfl_enc_0: 0.3911 (0.3911)  loss_bbox_enc_0: 1.5937 (1.5937)  loss_giou_enc_0: 1.8046 (1.8046)  loss_vfl_dn_0: 0.8760 (0.8760)  loss_bbox_dn_0: 0.8923 (0.8923)  loss_giou_dn_0: 1.3452 (1.3452)  loss_fgl_dn_0: 0.8456 (0.8456)  loss_vfl_dn_1: 0.8779 (0.8779)  loss_bbox_dn_1: 0.8923 (0.8923)  loss_giou_dn_1: 1.3452 (1.3452)  loss_fgl_dn_1: 0.8456 (0.8456)  loss_vfl_dn_2: 0.8154 (0.8154)  loss_bbox_dn_2: 0.8923 (0.8923)  loss_giou_dn_2: 1.3452 (1.3452)  loss_fgl_dn_2: 0.8456 (0.8456)  loss_vfl_dn_3: 0.8086 (0.8086)  loss_bbox_dn_3: 0.8923 (0.8923)  loss_giou_dn_3: 1.3452 (1.3452)  loss_fgl_dn_3: 0.8456 (0.8456)  loss_vfl_dn_4: 0.8193 (0.8193)  loss_bbox_dn_4: 0.8923 (0.8923)  loss_giou_dn_4: 1.3452 (1.3452)  loss_fgl_dn_4: 0.8456 (0.8456)  loss_vfl_dn_5: 0.8418 (0.8418)  loss_bbox_dn_5: 0.8923 (0.8923)  loss_giou_dn_5: 1.3452 (1.3452)  loss_fgl_dn_5: 0.8456 (0.8456)  loss_vfl_dn_pre: 0.8760 (0.8760)  loss_bbox_dn_pre: 0.8923 (0.8923)  loss_giou_dn_pre: 1.3452 (1.3452)  time: 2.2217  data: 1.2393  max mem: 15112
> Epoch: [0]  [ 100/7392]  eta: 1:13:07  lr: 0.000003  loss: 56.2025 (57.9531)  loss_vfl: 0.4348 (0.3721)  loss_bbox: 1.3989 (1.5938)  loss_giou: 1.7223 (1.8009)  loss_fgl: 0.4563 (0.4028)  loss_vfl_aux_0: 0.3728 (0.3391)  loss_bbox_aux_0: 1.4197 (1.6038)  loss_giou_aux_0: 1.7470 (1.8163)  loss_fgl_aux_0: 0.4463 (0.3969)  loss_vfl_aux_1: 0.4009 (0.3478)  loss_bbox_aux_1: 1.4084 (1.6003)  loss_giou_aux_1: 1.7344 (1.8108)  loss_fgl_aux_1: 0.4511 (0.3991)  loss_vfl_aux_2: 0.4009 (0.3517)  loss_bbox_aux_2: 1.4039 (1.5982)  loss_giou_aux_2: 1.7284 (1.8076)  loss_fgl_aux_2: 0.4523 (0.4003)  loss_vfl_aux_3: 0.4331 (0.3593)  loss_bbox_aux_3: 1.4011 (1.5964)  loss_giou_aux_3: 1.7252 (1.8048)  loss_fgl_aux_3: 0.4542 (0.4013)  loss_vfl_aux_4: 0.4377 (0.3639)  loss_bbox_aux_4: 1.3996 (1.5948)  loss_giou_aux_4: 1.7229 (1.8024)  loss_fgl_aux_4: 0.4557 (0.4022)  loss_vfl_pre: 0.3682 (0.3372)  loss_bbox_pre: 1.4252 (1.6057)  loss_giou_pre: 1.7543 (1.8191)  loss_vfl_enc_0: 0.3525 (0.3376)  loss_bbox_enc_0: 1.4507 (1.6135)  loss_giou_enc_0: 1.7840 (1.8316)  loss_vfl_dn_0: 0.6104 (0.7405)  loss_bbox_dn_0: 0.8605 (0.8423)  loss_giou_dn_0: 1.3456 (1.3426)  loss_fgl_dn_0: 0.8352 (0.8420)  loss_vfl_dn_1: 0.5996 (0.7327)  loss_bbox_dn_1: 0.8679 (0.8460)  loss_giou_dn_1: 1.3464 (1.3430)  loss_fgl_dn_1: 0.8299 (0.8406)  loss_vfl_dn_2: 0.5942 (0.7057)  loss_bbox_dn_2: 0.8700 (0.8487)  loss_giou_dn_2: 1.3474 (1.3434)  loss_fgl_dn_2: 0.8264 (0.8391)  loss_vfl_dn_3: 0.5928 (0.7130)  loss_bbox_dn_3: 0.8708 (0.8515)  loss_giou_dn_3: 1.3481 (1.3438)  loss_fgl_dn_3: 0.8233 (0.8377)  loss_vfl_dn_4: 0.6069 (0.7118)  loss_bbox_dn_4: 0.8698 (0.8544)  loss_giou_dn_4: 1.3489 (1.3442)  loss_fgl_dn_4: 0.8201 (0.8365)  loss_vfl_dn_5: 0.5972 (0.7139)  loss_bbox_dn_5: 0.8672 (0.8562)  loss_giou_dn_5: 1.3500 (1.3445)  loss_fgl_dn_5: 0.8192 (0.8356)  loss_vfl_dn_pre: 0.6128 (0.7413)  loss_bbox_dn_pre: 0.8571 (0.8407)  loss_giou_dn_pre: 1.3453 (1.3424)  loss_ddf_aux_0: 0.0046 (0.0020)  loss_ddf_aux_1: 0.0027 (0.0012)  loss_ddf_aux_2: 0.0015 (0.0007)  loss_ddf_aux_3: 0.0006 (0.0003)  loss_ddf_aux_4: 0.0002 (0.0001)  loss_ddf_dn_0: 0.0057 (0.0023)  loss_ddf_dn_1: 0.0035 (0.0016)  loss_ddf_dn_2: 0.0019 (0.0009)  loss_ddf_dn_3: 0.0008 (0.0004)  loss_ddf_dn_4: 0.0002 (0.0001)  time: 0.5679  data: 0.0320  max mem: 17561
> ```
> 
> Everything seems to be fine.

Does this startup command solve your problem?

**Comment by Peterande** [comment]
As the message states, "CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect," the error you provided may not reflect the actual issue. If you still encounter this problem, consider adding the following lines at the beginning of **train.py**:

```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```

Please remember to remove these two lines once the issue is resolved.

**Comment by Zailushang211** [comment]
> > RTX3090 reproduce, total batch size 16: `torchrun train.py -c configs/dfine/dfine_hgnetv2_${model}_coco.yml --use-amp --seed=0` ![image](https://private-user-images.githubusercontent.com/52695035/378725202-d93e4fb0-12c2-41eb-b29b-b78c13f6418d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ3NTQsIm5iZiI6MTczMDI3NDQ1NCwicGF0aCI6Ii81MjY5NTAzNS8zNzg3MjUyMDItZDkzZTRmYjAtMTJjMi00MWViLWIyOWItYjc4YzEzZjY0MThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzBjMGRmY2EzYzRlMDdlOGY3ZWE1NzE5MzIxOGEyMWVlZTFkNjczMWI2YTE5YWZiOTU1MGRlZmRkNjdlNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iBI692LVRz5R0Zc93w3fDDzPcBoMAtIqF-ytamxPR2I)
> > ```
> > 
> > Epoch: [0]  [   0/7392]  eta: 4:33:43  lr: 0.000000  loss: 59.3918 (59.3918)  loss_vfl: 0.3718 (0.3718)  loss_bbox: 1.5937 (1.5937)  loss_giou: 1.8046 (1.8046)  loss_fgl: 0.4020 (0.4020)  loss_vfl_aux_0: 0.4233 (0.4233)  loss_bbox_aux_0: 1.5937 (1.5937)  loss_giou_aux_0: 1.8046 (1.8046)  loss_fgl_aux_0: 0.4020 (0.4020)  loss_vfl_aux_1: 0.3875 (0.3875)  loss_bbox_aux_1: 1.5937 (1.5937)  loss_giou_aux_1: 1.8046 (1.8046)  loss_fgl_aux_1: 0.4020 (0.4020)  loss_vfl_aux_2: 0.3889 (0.3889)  loss_bbox_aux_2: 1.5937 (1.5937)  loss_giou_aux_2: 1.8046 (1.8046)  loss_fgl_aux_2: 0.4020 (0.4020)  loss_vfl_aux_3: 0.3877 (0.3877)  loss_bbox_aux_3: 1.5937 (1.5937)  loss_giou_aux_3: 1.8046 (1.8046)  loss_fgl_aux_3: 0.4020 (0.4020)  loss_vfl_aux_4: 0.3689 (0.3689)  loss_bbox_aux_4: 1.5937 (1.5937)  loss_giou_aux_4: 1.8046 (1.8046)  loss_fgl_aux_4: 0.4020 (0.4020)  loss_vfl_pre: 0.4233 (0.4233)  loss_bbox_pre: 1.5937 (1.5937)  loss_giou_pre: 1.8046 (1.8046)  loss_vfl_enc_0: 0.3911 (0.3911)  loss_bbox_enc_0: 1.5937 (1.5937)  loss_giou_enc_0: 1.8046 (1.8046)  loss_vfl_dn_0: 0.8760 (0.8760)  loss_bbox_dn_0: 0.8923 (0.8923)  loss_giou_dn_0: 1.3452 (1.3452)  loss_fgl_dn_0: 0.8456 (0.8456)  loss_vfl_dn_1: 0.8779 (0.8779)  loss_bbox_dn_1: 0.8923 (0.8923)  loss_giou_dn_1: 1.3452 (1.3452)  loss_fgl_dn_1: 0.8456 (0.8456)  loss_vfl_dn_2: 0.8154 (0.8154)  loss_bbox_dn_2: 0.8923 (0.8923)  loss_giou_dn_2: 1.3452 (1.3452)  loss_fgl_dn_2: 0.8456 (0.8456)  loss_vfl_dn_3: 0.8086 (0.8086)  loss_bbox_dn_3: 0.8923 (0.8923)  loss_giou_dn_3: 1.3452 (1.3452)  loss_fgl_dn_3: 0.8456 (0.8456)  loss_vfl_dn_4: 0.8193 (0.8193)  loss_bbox_dn_4: 0.8923 (0.8923)  loss_giou_dn_4: 1.3452 (1.3452)  loss_fgl_dn_4: 0.8456 (0.8456)  loss_vfl_dn_5: 0.8418 (0.8418)  loss_bbox_dn_5: 0.8923 (0.8923)  loss_giou_dn_5: 1.3452 (1.3452)  loss_fgl_dn_5: 0.8456 (0.8456)  loss_vfl_dn_pre: 0.8760 (0.8760)  loss_bbox_dn_pre: 0.8923 (0.8923)  loss_giou_dn_pre: 1.3452 (1.3452)  time: 2.2217  data: 1.2393  max mem: 15112
> > Epoch: [0]  [ 100/7392]  eta: 1:13:07  lr: 0.000003  loss: 56.2025 (57.9531)  loss_vfl: 0.4348 (0.3721)  loss_bbox: 1.3989 (1.5938)  loss_giou: 1.7223 (1.8009)  loss_fgl: 0.4563 (0.4028)  loss_vfl_aux_0: 0.3728 (0.3391)  loss_bbox_aux_0: 1.4197 (1.6038)  loss_giou_aux_0: 1.7470 (1.8163)  loss_fgl_aux_0: 0.4463 (0.3969)  loss_vfl_aux_1: 0.4009 (0.3478)  loss_bbox_aux_1: 1.4084 (1.6003)  loss_giou_aux_1: 1.7344 (1.8108)  loss_fgl_aux_1: 0.4511 (0.3991)  loss_vfl_aux_2: 0.4009 (0.3517)  loss_bbox_aux_2: 1.4039 (1.5982)  loss_giou_aux_2: 1.7284 (1.8076)  loss_fgl_aux_2: 0.4523 (0.4003)  loss_vfl_aux_3: 0.4331 (0.3593)  loss_bbox_aux_3: 1.4011 (1.5964)  loss_giou_aux_3: 1.7252 (1.8048)  loss_fgl_aux_3: 0.4542 (0.4013)  loss_vfl_aux_4: 0.4377 (0.3639)  loss_bbox_aux_4: 1.3996 (1.5948)  loss_giou_aux_4: 1.7229 (1.8024)  loss_fgl_aux_4: 0.4557 (0.4022)  loss_vfl_pre: 0.3682 (0.3372)  loss_bbox_pre: 1.4252 (1.6057)  loss_giou_pre: 1.7543 (1.8191)  loss_vfl_enc_0: 0.3525 (0.3376)  loss_bbox_enc_0: 1.4507 (1.6135)  loss_giou_enc_0: 1.7840 (1.8316)  loss_vfl_dn_0: 0.6104 (0.7405)  loss_bbox_dn_0: 0.8605 (0.8423)  loss_giou_dn_0: 1.3456 (1.3426)  loss_fgl_dn_0: 0.8352 (0.8420)  loss_vfl_dn_1: 0.5996 (0.7327)  loss_bbox_dn_1: 0.8679 (0.8460)  loss_giou_dn_1: 1.3464 (1.3430)  loss_fgl_dn_1: 0.8299 (0.8406)  loss_vfl_dn_2: 0.5942 (0.7057)  loss_bbox_dn_2: 0.8700 (0.8487)  loss_giou_dn_2: 1.3474 (1.3434)  loss_fgl_dn_2: 0.8264 (0.8391)  loss_vfl_dn_3: 0.5928 (0.7130)  loss_bbox_dn_3: 0.8708 (0.8515)  loss_giou_dn_3: 1.3481 (1.3438)  loss_fgl_dn_3: 0.8233 (0.8377)  loss_vfl_dn_4: 0.6069 (0.7118)  loss_bbox_dn_4: 0.8698 (0.8544)  loss_giou_dn_4: 1.3489 (1.3442)  loss_fgl_dn_4: 0.8201 (0.8365)  loss_vfl_dn_5: 0.5972 (0.7139)  loss_bbox_dn_5: 0.8672 (0.8562)  loss_giou_dn_5: 1.3500 (1.3445)  loss_fgl_dn_5: 0.8192 (0.8356)  loss_vfl_dn_pre: 0.6128 (0.7413)  loss_bbox_dn_pre: 0.8571 (0.8407)  loss_giou_dn_pre: 1.3453 (1.3424)  loss_ddf_aux_0: 0.0046 (0.0020)  loss_ddf_aux_1: 0.0027 (0.0012)  loss_ddf_aux_2: 0.0015 (0.0007)  loss_ddf_aux_3: 0.0006 (0.0003)  loss_ddf_aux_4: 0.0002 (0.0001)  loss_ddf_dn_0: 0.0057 (0.0023)  loss_ddf_dn_1: 0.0035 (0.0016)  loss_ddf_dn_2: 0.0019 (0.0009)  loss_ddf_dn_3: 0.0008 (0.0004)  loss_ddf_dn_4: 0.0002 (0.0001)  time: 0.5679  data: 0.0320  max mem: 17561
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything seems to be fine.
> 
> Does this startup command solve your problem?

Thank you very much for your quick reply.  This command worked well with the config configs/dfine/dfine_hgnetv2_x_coco.yml, it raised the same error if i use configs/dfine/custom/dfine_hgnetv2_x_custom.yml as indicated in readme file, not sure if i misunderstand something.
Will go on with the coco config. Thanks again.

**Comment by Peterande** [comment]
You need to modify this, probably:
https://github.com/Peterande/D-FINE/blob/4e8d80f7a241d06ebab052b47a03e720c0794de9/configs/dataset/custom_detection.yml#L7

**Comment by Zailushang211** [comment]
I just checked that the problem is caused by remap_mscoco_category: False, a True value works well. if my classes don't belong to the coco categrories, and i just changed my num_classes to mine, would this be a problem?

**Comment by Peterande** [comment]
This seems to indicate that your class labels do not start from 0 and may be non-sequential, which causes the largest class to be greater than `num_classes - 1`. Modifying `mscoco_category2name` to match the labels of your dataset could be a potential solution.

https://github.com/Peterande/D-FINE/blob/6cde0b803633ff5450045f1ec818a1fc0ec92d10/src/data/dataset/coco_dataset.py#L178-L259

**Comment by Zailushang211** [comment]
I test with only one classes as:
{
      "id": 30056,
      "image_id": 2658,
      "category_id": 1,
      "bbox": [
        328.99968,
        72.0,
        96.0,
        101.00016000000001
      ],
      "area": 9696.015360000001,
      "iscrowd": 0
    },
and set num_classes=1, is this the problem? should i change the categroy_id to 0 ? but the index in [D-FINE/src/data/dataset/coco_dataset.py](https://github.com/Peterande/D-FINE/blob/6cde0b803633ff5450045f1ec818a1fc0ec92d10/src/data/dataset/coco_dataset.py#L178-L259) also start from 1 as seen.

**Comment by Peterande** [comment]
You are right! Index in [D-FINE/src/data/dataset/coco_dataset.py](https://github.com/Peterande/D-FINE/blob/6cde0b803633ff5450045f1ec818a1fc0ec92d10/src/data/dataset/coco_dataset.py#L178-L259) is the ids before mapping. 
See this:
![image](https://github.com/user-attachments/assets/18a559ac-5745-41e5-ab0a-5b19b6a0d1b9)
1 will be mapped to 0~

**Comment by Zailushang211** [comment]
thanks a lot for your patience.

**Comment by Peterande** [comment]
You're welcome

**Comment by 309020726** [comment]
> 我刚刚检查了问题是由 remap_mscoco_category：False 引起的，True 值运行良好。如果我的类不属于 Coco 分类，而我只是将 num_classes 更改为我的类，这会有问题吗？


Have you solved this problem? If my own dataset category is not in obj365, should I modify the category name mapping? Where should I modify it?
