### ISSUE TITLE
yolov5与Dfine的精度比较

### ISSUE THREAD

**Issue by iangiu** [Peterande/D-FINE#106]
作者您好，近期我使用您提出的算法，比较了多个私有数据集上yolov5s/yolov5n与Dfine-s/Dfine-n的精度，但是发现AP50精度并没有比yolov5更好，在其中有个数据集，有着些微程度的下降（yolov5s比dfine-s高0.5个点左右）也就是没有明显的提升。

以下是算法的条件设置：
1. 首先我使用了obj365的模型进行私有数据集的微调操作，而后查看了计算俩者计算AP的方式（都是使用coco的计算方式，采样101个点），所以排除了计算AP差异的可能性。
2. yolov5训练时，打开了rect的参数即矩形输入。dfine训练时，调整了transform的resize成矩形输入。
3. dfine的其他超参数基本上是默认值，只改了batchsize为24g能支持的显存尺寸。yolov5的超参数也是默认的。
4. 数据集采用coco格式，数据集规模为训练集约12000张图片，验证集约1200张图片。
5. 除此以外，还进行了trt-fp16的速度测试，3080ti的显卡下，图像输入尺寸为864*864，yolov5s-nms阈值设为（conf：0.01 iou：0.7 max_output_boxes：300）。yolov5s耗时为0.0010s，dfine-s耗时为0.0023s。

以下是疑问：

1. 请问作者有什么建议对于我使用以上的方式训练，对于提升精度的目的下，超参数可以怎么调整呢。或者说可能是数据集本身的原因，造成精度已经无法提升了。不知道作者有这种问题解决的经验么。
2. 观察到一个问题，在其中一个数据集上，dfine-n的指标mAP0.5:0.95只比yolov5s差1%，但是mAP50比yolov5s差7%。这个现象我有点不太理解，这是因为数据集本身的特性造成的么。
3. 在速度比较场景下，耗时大小虽说对于nms的conf阈值很敏感。但是在实际应用过程中，推理时nms的conf实际会设成0.1或0.2，这样会过滤掉很多无用的框，并且并不太影响检测精度，如此一来对于整个推理过程nms的耗时影响好像并没有太大，最终nms free的过程好像并没有太大的实际增益。不知道这样理解合不合理。希望作者能解答疑惑。

最后，非常感谢作者的工作，也希望作者抽空可以解答疑惑。

**Comment by Peterande** [comment]
感谢您的尝试~
在我的观察中，大型数据集（如Objects365) 的预训练能够显著改善同样类别较多、场景复杂的数据集（如COCO）的检测能力。
这个收益本质上来源于模型从大规模数据分布中凝练的“场景、类别知识”。

**但私有数据集往往类别少、场景重复，在这些数据集用预训练的模型会很容易导致过拟合。**
**我更建议尝试 training from scratch。**

ps: 比如我在**CrowdHuman**数据集上，使用预训练会比直接训性能差数个点。

**Comment by iangiu** [comment]
> 另外：
> 
> 1. 不调整transform的resize成矩形输入会不会变好。
> 2. 改了batchsize后，最好根据README改一下其他超参，README里有写怎么改。
> 3. 关于NMS，你可以尝试测一下NMS置信度阈值为0.01时的mAP，差距和0.001还是挺显著的。我在与YOLO11比较的时候也是改了他的阈值测了的，你可以看一下teaser图。另外，你的测速我不确定是否两个测速代码是否一致，因为NMS在不同图片的处理时间是完全不一样的，密集的场景处理时间很长、稀疏的场景比如只有一个物体可能几乎不耗时。我们的速度都是数据集所有图片的平均结果，不能只看一张图。

谢谢回复，那我先尝试一下。

**Comment by iangiu** [comment]
> 另外：
> 
> 1. 不调整transform的resize成矩形输入会不会变好。
> 2. 改了batchsize后，最好根据README改一下其他超参，README里有写怎么改。
> 3. 关于NMS，你可以尝试测一下NMS置信度阈值为0.01时的mAP，差距和0.001还是挺显著的。我在与YOLO11比较的时候也是改了他的阈值测了的，你可以看一下teaser图。另外，你的测速我不确定是否两个测速代码是否一致，因为NMS在不同图片的处理时间是完全不一样的，密集的场景处理时间很长、稀疏的场景比如只有一个物体可能几乎不耗时。我们的速度都是数据集所有图片的平均结果，不能只看一张图。

尝试了作者的建议，经过调参，目前矩形与方形的精度基本保持了一致，原图是矩形的数据集，矩形输入的时候，收敛的会更快，但最终的指标基本差不多。
