### ISSUE TITLE
D-FINE-n系列

### ISSUE THREAD

**Issue by hpc203** [Peterande/D-FINE#11]
我用D-FINE-S系列的训练完成之后，导出onnx文件，有40M的大小，这个部署在嵌入式板子上，算力有些吃紧了。
博主能推出一个D-FINE-n系列的嘛，像YOLO11-n那样子的

**Comment by Peterande** [comment]
你好~因为s的backbone已经是HGNetV2的最小版本了，因为不想重新在ImageNet上预训练一遍HGNetV2，所以没做n。后面会考虑看看有没有其他可以替代的选择。
