### ISSUE TITLE
How many images are required for sufficent training?

### ISSUE THREAD

**Issue by ShpihanVlad** [Peterande/D-FINE#123]
Hello, from what I understand, this model has DETR components, so does it make it data hungry, like other transformer models, or smaller amount of images, requireed for CNN-based models, such as YOLO, with which this model is compared, is enough?

**Comment by masc-it** [comment]
ofc it depends on your task, you need to experiment but yeah, as generally with Transformer-based models, you need more than some hundreds of samples. If you have a small datasets, first try with the nano config that builds a model of 2M-3M params

**Comment by ShpihanVlad** [comment]
Thanks, got it
