### ISSUE TITLE
训练速度慢、ONNX转换出错

### ISSUE THREAD

**Issue by XHoio** [Peterande/D-FINE#13]
(D_FINE) ➜  D_FINE CUDA_VISIBLE_DEVICES=1,4,5,6 torchrun --master_port=7777 --nproc_per_node=4 train.py -c configs/dfine/custom/dfine_hgnetv2_${model}_custom.yml --use-amp --seed=0
[2024-10-30 19:35:14,844] torch.distributed.run: [WARNING] 
[2024-10-30 19:35:14,844] torch.distributed.run: [WARNING] *****************************************
[2024-10-30 19:35:14,844] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-10-30 19:35:14,844] torch.distributed.run: [WARNING] *****************************************
Initialized distributed mode...
cfg:  {'task': 'detection', '_model': None, '_postprocessor': None, '_criterion': None, '_optimizer': None, '_lr_scheduler': None, '_lr_warmup_scheduler': None, '_train_dataloader': None, '_val_dataloader': None, '_ema': None, '_scaler': None, '_train_dataset': None, '_val_dataset': None, '_collate_fn': None, '_evaluator': None, '_writer': None, 'num_workers': 0, 'batch_size': None, '_train_batch_size': None, '_val_batch_size': None, '_train_shuffle': None, '_val_shuffle': None, 'resume': None, 'tuning': None, 'epoches': 132, 'last_epoch': -1, 'use_amp': True, 'use_ema': True, 'ema_decay': 0.9999, 'ema_warmups': 2000, 'sync_bn': True, 'clip_max_norm': 0.1, 'find_unused_parameters': False, 'seed': 0, 'print_freq': 100, 'checkpoint_freq': 12, 'output_dir': './output/dfine_hgnetv2_s_custom', 'summary_dir': None, 'device': '', 'yaml_cfg': {'task': 'detection', 'evaluator': {'type': 'CocoEvaluator', 'iou_types': ['bbox']}, 'num_classes': 4, 'remap_mscoco_category': False, 'train_dataloader': {'type': 'DataLoader', 'dataset': {'type': 'CocoDetection', 'img_folder': '/home/ubuntu/projects/lcc/dk52/RT-DETR/rtdetrv2_pytorch/dataset/GT_dtv2D_gzt_not0txt_cls4_20241009/train', 'ann_file': '/home/ubuntu/projects/lcc/dk52/RT-DETR/rtdetrv2_pytorch/dataset/GT_dtv2D_gzt_not0txt_cls4_20241009/annotations/train.json', 'return_masks': False, 'transforms': {'type': 'Compose', 'ops': [{'type': 'RandomPhotometricDistort', 'p': 0.5}, {'type': 'RandomZoomOut', 'fill': 0}, {'type': 'RandomIoUCrop', 'p': 0.0}, {'type': 'SanitizeBoundingBoxes', 'min_size': 1}, {'type': 'RandomHorizontalFlip'}, {'type': 'Resize', 'size': [640, 640]}, {'type': 'SanitizeBoundingBoxes', 'min_size': 1}, {'type': 'ConvertPILImage', 'dtype': 'float32', 'scale': True}, {'type': 'ConvertBoxes', 'fmt': 'cxcywh', 'normalize': True}], 'policy': {'name': 'stop_epoch', 'epoch': 120, 'ops': ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']}}}, 'shuffle': True, 'num_workers': 4, 'drop_last': True, 'collate_fn': {'type': 'BatchImageCollateFuncion', 'base_size': 640, 'base_size_repeat': 20, 'stop_epoch': 120, 'ema_restart_decay': 0.9999}, 'total_batch_size': 64}, 'val_dataloader': {'type': 'DataLoader', 'dataset': {'type': 'CocoDetection', 'img_folder': '/home/ubuntu/projects/lcc/dk52/RT-DETR/rtdetrv2_pytorch/dataset/GT_dtv2D_gzt_not0txt_cls4_20241009/val', 'ann_file': '/home/ubuntu/projects/lcc/dk52/RT-DETR/rtdetrv2_pytorch/dataset/GT_dtv2D_gzt_not0txt_cls4_20241009/annotations/val.json', 'return_masks': False, 'transforms': {'type': 'Compose', 'ops': [{'type': 'Resize', 'size': [640, 640]}, {'type': 'ConvertPILImage', 'dtype': 'float32', 'scale': True}]}}, 'shuffle': False, 'num_workers': 4, 'drop_last': False, 'collate_fn': {'type': 'BatchImageCollateFuncion'}, 'total_batch_size': 64}, 'print_freq': 100, 'output_dir': './output/dfine_hgnetv2_s_custom', 'checkpoint_freq': 12, 'sync_bn': True, 'find_unused_parameters': False, 'use_amp': True, 'scaler': {'type': 'GradScaler', 'enabled': True}, 'use_ema': True, 'ema': {'type': 'ModelEMA', 'decay': 0.9999, 'warmups': 1000, 'start': 0}, 'epoches': 132, 'clip_max_norm': 0.1, 'optimizer': {'type': 'AdamW', 'params': [{'params': '^(?=.*backbone)(?!.*norm|bn).*$', 'lr': 0.0001}, {'params': '^(?=.*backbone)(?=.*norm|bn).*$', 'lr': 0.0001, 'weight_decay': 0.0}, {'params': '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$', 'weight_decay': 0.0}], 'lr': 0.0002, 'betas': [0.9, 0.999], 'weight_decay': 0.0001}, 'lr_scheduler': {'type': 'MultiStepLR', 'milestones': [500], 'gamma': 0.1}, 'lr_warmup_scheduler': {'type': 'LinearWarmup', 'warmup_duration': 500}, 'model': 'DFINE', 'criterion': 'DFINECriterion', 'postprocessor': 'DFINEPostProcessor', 'use_focal_loss': True, 'eval_spatial_size': [640, 640], 'DFINE': {'backbone': 'HGNetv2', 'encoder': 'HybridEncoder', 'decoder': 'DFINETransformer'}, 'HGNetv2': {'pretrained': True, 'local_model_dir': 'weight/hgnetv2/', 'name': 'B0', 'return_idx': [1, 2, 3], 'freeze_at': -1, 'freeze_norm': False, 'use_lab': True}, 'HybridEncoder': {'in_channels': [256, 512, 1024], 'feat_strides': [8, 16, 32], 'hidden_dim': 256, 'use_encoder_idx': [2], 'num_encoder_layers': 1, 'nhead': 8, 'dim_feedforward': 1024, 'dropout': 0.0, 'enc_act': 'gelu', 'expansion': 0.5, 'depth_mult': 0.34, 'act': 'silu'}, 'DFINETransformer': {'feat_channels': [256, 256, 256], 'feat_strides': [8, 16, 32], 'hidden_dim': 256, 'num_levels': 3, 'num_layers': 3, 'eval_idx': -1, 'num_queries': 300, 'num_denoising': 100, 'label_noise_ratio': 0.5, 'box_noise_scale': 1.0, 'reg_max': 32, 'reg_scale': 4, 'layer_scale': 1, 'num_points': [3, 6, 3], 'cross_attn_method': 'default', 'query_select_method': 'default'}, 'DFINEPostProcessor': {'num_top_queries': 300}, 'DFINECriterion': {'weight_dict': {'loss_vfl': 1, 'loss_bbox': 5, 'loss_giou': 2, 'loss_fgl': 0.15, 'loss_ddf': 1.5}, 'losses': ['vfl', 'boxes', 'local'], 'alpha': 0.75, 'gamma': 2.0, 'reg_max': 32, 'matcher': {'type': 'HungarianMatcher', 'weight_dict': {'cost_class': 2, 'cost_bbox': 5, 'cost_giou': 2}, 'alpha': 0.25, 'gamma': 2.0}}, '__include__': ['../../dataset/custom_detection.yml', '../../runtime.yml', '../include/dataloader.yml', '../include/optimizer.yml', '../include/dfine_hgnetv2.yml'], 'config': 'configs/dfine/custom/dfine_hgnetv2_s_custom.yml', 'seed': 0, 'test_only': False, 'print_method': 'builtin', 'print_rank': 0}}
Loaded stage1 B0 HGNetV2 from local file.
Initial lr: [0.0001, 0.0001, 0.0002, 0.0002]
building train_dataloader with batch_size=16...
loading annotations into memory...
Done (t=0.36s)
creating index...
index created!
building val_dataloader with batch_size=16...
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!

------------------------------------- Calculate Flops Results -------------------------------------
Notations:
number of parameters (Params), number of multiply-accumulate operations(MACs),
number of floating-point operations (FLOPs), floating-point operations per second (FLOPS),
fwd FLOPs (model forward propagation FLOPs), bwd FLOPs (model backward propagation FLOPs),
default model backpropagation takes 2.00 times as much computation as forward propagation.

Total Training Params:                                                  10.18 M 
fwd MACs:                                                               12.363 GMACs
fwd FLOPs:                                                              24.8328 GFLOPS
fwd+bwd MACs:                                                           37.0891 GMACs
fwd+bwd FLOPs:                                                          74.4984 GFLOPS
---------------------------------------------------------------------------------------------------
{'Model FLOPs:24.8328 GFLOPS   MACs:12.363 GMACs   Params:10178971'}
------------------------------------------Start training-------------------------------------------
Epoch: [0]  [  0/176]  eta: 1:10:16  lr: 0.000000  loss: 51.1275 (51.1275)  loss_bbox: 4.3128 (4.3128)  loss_bbox_aux_0: 4.3128 (4.3128)  loss_bbox_aux_1: 4.3128 (4.3128)  loss_bbox_dn_0: 1.9389 (1.9389)  loss_bbox_dn_1: 1.9389 (1.9389)  loss_bbox_dn_2: 1.9389 (1.9389)  loss_bbox_dn_pre: 1.9389 (1.9389)  loss_bbox_enc_0: 4.3128 (4.3128)  loss_bbox_pre: 4.3128 (4.3128)  loss_fgl: 0.1732 (0.1732)  loss_fgl_aux_0: 0.1732 (0.1732)  loss_fgl_aux_1: 0.1732 (0.1732)  loss_fgl_dn_0: 0.8813 (0.8813)  loss_fgl_dn_1: 0.8813 (0.8813)  loss_fgl_dn_2: 0.8813 (0.8813)  loss_giou: 1.9120 (1.9120)  loss_giou_aux_0: 1.9120 (1.9120)  loss_giou_aux_1: 1.9120 (1.9120)  loss_giou_dn_0: 1.2848 (1.2848)  loss_giou_dn_1: 1.2848 (1.2848)  loss_giou_dn_2: 1.2848 (1.2848)  loss_giou_dn_pre: 1.2848 (1.2848)  loss_giou_enc_0: 1.9120 (1.9120)  loss_giou_pre: 1.9120 (1.9120)  loss_vfl: 0.1176 (0.1176)  loss_vfl_aux_0: 0.1197 (0.1197)  loss_vfl_aux_1: 0.1176 (0.1176)  loss_vfl_dn_0: 0.8148 (0.8148)  loss_vfl_dn_1: 0.8992 (0.8992)  loss_vfl_dn_2: 0.8214 (0.8214)  loss_vfl_dn_pre: 0.8148 (0.8148)  loss_vfl_enc_0: 0.1199 (0.1199)  loss_vfl_pre: 0.1197 (0.1197)  time: 23.9598  data: 10.0737  max mem: 6707
Epoch: [0]  [100/176]  eta: 0:03:29  lr: 0.000020  loss: 38.3745 (41.4032)  loss_bbox: 1.8019 (2.6033)  loss_bbox_aux_0: 1.7953 (2.6397)  loss_bbox_aux_1: 1.7968 (2.6194)  loss_bbox_dn_0: 1.6007 (1.5815)  loss_bbox_dn_1: 1.6275 (1.5904)  loss_bbox_dn_2: 1.6347 (1.6061)  loss_bbox_dn_pre: 1.5850 (1.5764)  loss_bbox_enc_0: 2.0097 (2.7025)  loss_bbox_pre: 1.8164 (2.6547)  loss_fgl: 0.9912 (0.5893)  loss_fgl_aux_0: 0.9981 (0.5820)  loss_fgl_aux_1: 0.9980 (0.5868)  loss_fgl_dn_0: 0.8740 (0.8622)  loss_fgl_dn_1: 0.8718 (0.8617)  loss_fgl_dn_2: 0.8693 (0.8608)  loss_giou: 1.0497 (1.4870)  loss_giou_aux_0: 1.0463 (1.5001)  loss_giou_aux_1: 1.0468 (1.4924)  loss_giou_dn_0: 1.3033 (1.3164)  loss_giou_dn_1: 1.3053 (1.3168)  loss_giou_dn_2: 1.3086 (1.3178)  loss_giou_dn_pre: 1.3016 (1.3161)  loss_giou_enc_0: 1.1653 (1.5355)  loss_giou_pre: 1.0567 (1.5071)  loss_vfl: 0.9315 (0.5313)  loss_vfl_aux_0: 0.9689 (0.5103)  loss_vfl_aux_1: 0.9591 (0.5325)  loss_vfl_dn_0: 0.3807 (0.5390)  loss_vfl_dn_1: 0.3813 (0.5682)  loss_vfl_dn_2: 0.3716 (0.5022)  loss_vfl_dn_pre: 0.3814 (0.5394)  loss_vfl_enc_0: 0.8380 (0.4690)  loss_vfl_pre: 0.9890 (0.5028)  loss_ddf_aux_0: 0.0055 (0.0016)  loss_ddf_aux_1: 0.0009 (0.0004)  loss_ddf_dn_0: 0.0009 (0.0004)  loss_ddf_dn_1: 0.0002 (0.0001)  time: 2.4388  data: 0.5906  max mem: 9660
作者您好，打扰您，我在使用您的代码的时候遇到了一些问题，希望您有空的时候能够帮忙看一下。
以上是我的训练日志，我一直在反复的调节total_batch_size，调节下来的总结就是似乎我4个GPU（单个48G显存）只能设置total_batch_size为64，再往上加就会报错RuntimeError: received 0 items of ancdata，不确定是哪里的问题。目前一个epoch需要花费10分钟吧，是正常的吗？我的数据量也不大，训练加验证就1万3左右的图片数量。这让我很困惑。我试过把torch.multiprocessing.set_sharing_strategy('file_system')，但是这并不是一个好的方法。程序会卡住不动。

**Comment by Peterande** [comment]
1. `ulimit -n 2048`指令能解决`RuntimeError: received 0 items of ancdata`的问题吗？这似乎是数据集读取相关的问题，https://stackoverflow.com/questions/71642653/how-to-resolve-the-error-runtimeerror-received-0-items-of-ancdata
2. 在这里加上persistent_workers=True会让训练从第二个epoch开始变快吗？ https://github.com/Peterande/D-FINE/blob/c060d5bcd27167d5e44faae85f69e0330281f1eb/src/misc/dist_utils.py#L157-L163 
3. 目前的GPU利用率能跑到多少？

**Comment by XHoio** [comment]
我修改了ulimit -n 2048，persistent_workers=True，GPU利用率是个浮动值，在50-100%之间横跳。这些修改并未能让我的训练提速，他依旧很慢。也许是我的数据存在问题，PIL库读取时还报了警告：Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack. 可是我写过脚本查看过，我并没有那么大的图片。我对这个问题暂时没有头绪和思路了。
![img1](https://github.com/user-attachments/assets/471380bd-79ce-4266-8d5a-dbcc8507f53d)
![img2](https://github.com/user-attachments/assets/14181353-eaf4-49a6-9019-02f5c3fa6bbf)

**Comment by Peterande** [comment]
请问你使用的数据集是公开数据集吗?最高像素大概是多少。
我在Objects365上最开始也遇到了`Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack`警告，我的处理方法是将所以超过640*640的图片提前resize:
https://github.com/Peterande/D-FINE/blob/master/tools/dataset/resize_obj365.py

**Comment by Peterande** [comment]
速度慢的原因很大概率是每个epoch前一小部分step的预热慢，因为你每个epoch的step数太少了，可以考虑将数据集的json文件复制N倍，把N倍的数据放在一个epoch。

**Comment by XHoio** [comment]
作者你好，我训练的是自由数据集。今早过来看跑到了100epoch。当我使用python /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py --check -c /home/ubuntu/projects/lcc/dk52/D_FINE/configs/dfine/custom/dfine_hgnetv2_s_custom.yml -r /home/ubuntu/projects/lcc/dk52/D_FINE/output/dfine_hgnetv2_s_custom/best.pth      

这让我产生的错误/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/zoo/dfine/dfine_decoder.py:642: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if memory.shape[0] > 1:
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/zoo/dfine/dfine_decoder.py:129: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/zoo/dfine/dfine_decoder.py:133: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif reference_points.shape[-1] == 4:
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/_internal/jit_utils.py:307: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ../torch/csrc/jit/passes/onnx/constant_fold.cpp:179.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
Traceback (most recent call last):
  File "/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py", line 103, in <module>
    main(args)
  File "/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py", line 65, in main
    torch.onnx.export(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py", line 1139, in _model_to_graph
    graph = _optimize_graph(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py", line 677, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py", line 1940, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 395, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_opset10.py", line 203, in symbolic_fn
    padding_ceil = opset9.get_pool_ceil_padding(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_opset9.py", line 1565, in get_pool_ceil_padding
    return symbolic_helper._unimplemented(
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 612, in _unimplemented
    _onnx_unsupported(f"{op}, {msg}", value)
  File "/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py", line 623, in _onnx_unsupported
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator get_pool_ceil_padding, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value 'input.8 defined in (%input.8 : Float(*, *, *, *, strides=[1648656, 103041, 321, 1], requires_grad=1, device=cpu) = onnx::Pad[mode="constant"](%563, %589, %550), scope: __main__.main.<locals>.Model::/src.zoo.dfine.dfine.DFINE::model/src.nn.backbone.hgnetv2.HGNetv2::backbone/src.nn.backbone.hgnetv2.StemBlock::stem # /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py:168:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Pad'.] 
    (node defined in /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py(168): forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1508): _slow_forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1527): _call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py(537): forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1508): _slow_forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1527): _call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/zoo/dfine/dfine.py(27): forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1508): _slow_forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1527): _call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py(48): forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1508): _slow_forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1527): _call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/jit/_trace.py(124): wrapper
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/jit/_trace.py(133): forward
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1527): _call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/jit/_trace.py(1285): _get_trace_graph
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py(915): _trace_and_get_graph_from_model
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py(1011): _create_jit_graph
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py(1135): _model_to_graph
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py(1596): _export
/home/ubuntu/anaconda3/envs/D_FINE/lib/python3.10/site-packages/torch/onnx/utils.py(516): export
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py(65): main
/home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/export_onnx.py(103): <module>
)

    Inputs:
        #0: 563 defined in (%563 : Float(*, 16, 320, 320, strides=[1638400, 102400, 320, 1], requires_grad=1, device=cpu) = onnx::Add(%562, %model.backbone.stem.stem1.lab.bias), scope: __main__.main.<locals>.Model::/src.zoo.dfine.dfine.DFINE::model/src.nn.backbone.hgnetv2.HGNetv2::backbone/src.nn.backbone.hgnetv2.StemBlock::stem/src.nn.backbone.hgnetv2.ConvBNAct::stem1/src.nn.backbone.hgnetv2.LearnableAffineBlock::lab # /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py:35:0
    )  (type 'Tensor')
        #1: 589 defined in (%589 : Long(8, strides=[1], device=cpu) = onnx::Cast[to=7](%588), scope: __main__.main.<locals>.Model::/src.zoo.dfine.dfine.DFINE::model/src.nn.backbone.hgnetv2.HGNetv2::backbone/src.nn.backbone.hgnetv2.StemBlock::stem # /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py:168:0
    )  (type 'Tensor')
        #2: 550 defined in (%550 : NoneType = prim::Constant(), scope: __main__.main.<locals>.Model::/src.zoo.dfine.dfine.DFINE::model/src.nn.backbone.hgnetv2.HGNetv2::backbone/src.nn.backbone.hgnetv2.StemBlock::stem/src.nn.backbone.hgnetv2.ConvBNAct::stem1/torch.nn.modules.conv.Conv2d::conv
    )  (type 'NoneType')
    Outputs:
        #0: input.8 defined in (%input.8 : Float(*, *, *, *, strides=[1648656, 103041, 321, 1], requires_grad=1, device=cpu) = onnx::Pad[mode="constant"](%563, %589, %550), scope: __main__.main.<locals>.Model::/src.zoo.dfine.dfine.DFINE::model/src.nn.backbone.hgnetv2.HGNetv2::backbone/src.nn.backbone.hgnetv2.StemBlock::stem # /home/ubuntu/projects/lcc/dk52/D_FINE/tools/deployment/../../src/nn/backbone/hgnetv2.py:168:0
    )  (type 'Tensor') 我该怎么解决

**Comment by Peterande** [comment]
你好👋
看上去转onnx的过程中遇到了不支持的操作。请问你对网络代码进行过修改吗？现在onnx相关包的版本都是多少，升级到最新版本可以解决吗？

**Comment by XHoio** [comment]
![image](https://github.com/user-attachments/assets/e74acc6a-d0a4-4d36-a0e0-b22c7bf1b481)
我更新了onnx，但是我依旧还是出现上述同样的问题。我也并没有修改过网络结构。

**Comment by Peterande** [comment]
问题似乎指向
https://github.com/Peterande/D-FINE/blob/6a30d8dca869c7a3b2fb816b7599fe5e686288dc/src/nn/backbone/hgnetv2.py#L164
但我并没有在转onnx的过程中遇到过类似的问题，如果代码没有任何修改，这很奇怪。
我在检索的时候看到有人建议升级torch，可以参考[url](https://github.com/pytorch/pytorch/issues/113155)

**Comment by XHoio** [comment]
![image](https://github.com/user-attachments/assets/348d11f7-0414-4282-821a-6b7d920dfb82)
作者你好，通过升级torch我已经解决了我的问题，已经成功转成了onnx。
环境适配：pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
touch用的222，CUDA用的118。谢谢您的指导。

**Comment by Peterande** [comment]
不客气~

**Comment by wanjunling168** [comment]
> 请问你使用的数据集是公开数据集吗?最高像素大概是多少。 我在Objects365上最开始也遇到了`Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack`警告，我的处理方法是将所以超过640*640的图片提前resize: https://github.com/Peterande/D-FINE/blob/master/tools/dataset/resize_obj365.py

@Peterande 看这个：https://github.com/ultralytics/yolov5/issues/7003#issuecomment-1795894118，也许可以试下`from PIL import Image`的时候改一下？
```
# Increase the pixel limit
Image.MAX_IMAGE_PIXELS = None  # or set to a larger value like 933120000
```

**Comment by Peterande** [comment]
> > 请问你使用的数据集是公开数据集吗?最高像素大概是多少。 我在Objects365上最开始也遇到了`Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack`警告，我的处理方法是将所以超过640*640的图片提前resize: https://github.com/Peterande/D-FINE/blob/master/tools/dataset/resize_obj365.py
> 
> @Peterande 看这个：`https://github.com/ultralytics/yolov5/issues/7003#issuecomment-1795894118`，也许可以试下`from PIL import Image`的时候改一下？
> 
> ```
> # Increase the pixel limit
> Image.MAX_IMAGE_PIXELS = None  # or set to a larger value like 933120000
> ```

这个方案我试过，但Objects365数据集还有一些损坏的文件，设置了以后还会报错。而且把超大像素的图片在训练过程中resize效率较低，索性就直接提前resize了

**Comment by wanjunling168** [comment]
> > > 请问你使用的数据集是公开数据集吗?最高像素大概是多少。 我在Objects365上最开始也遇到了`Image size (324768098 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack`警告，我的处理方法是将所以超过640*640的图片提前resize: https://github.com/Peterande/D-FINE/blob/master/tools/dataset/resize_obj365.py
> > 
> > 
> > @Peterande 看这个：`https://github.com/ultralytics/yolov5/issues/7003#issuecomment-1795894118`，也许可以试下`from PIL import Image`的时候改一下？
> > ```
> > # Increase the pixel limit
> > Image.MAX_IMAGE_PIXELS = None  # or set to a larger value like 933120000
> > ```
> 
> 这个方案我试过，但Objects365数据集还有一些损坏的文件，设置了以后还会报错。而且把超大像素的图片在训练过程中resize效率较低，索性就直接提前resize了

倒也是，CPU上resize效率太低了，除非上DALI那些来做GPU预处理，但那玩意有点重过头了:(
