### ISSUE TITLE
怎么对自己的数据集进行测试的可视化

### ISSUE THREAD

**Issue by yaosx425** [Peterande/D-FINE#14]
作者您好！在训练自己的数据集之后，我想进行测试，怎么进行测试结果的可视化呢？

**Comment by Peterande** [comment]
你好~刚刚加入了视频推理的支持：
![image](https://github.com/user-attachments/assets/90f74ca9-cf9c-4635-8598-7396f7b21367)
为了保证代码简洁，方便修改，并没有对输出框进行美化，你可以根据需要加粗边框、变更颜色等。

**Comment by yaosx425** [comment]
> 你好~如果你不想使用[Fiftyone](https://github.com/voxel51/fiftyone)，也可以直接用训练好的模型进行推理： ![image](https://private-user-images.githubusercontent.com/52695035/381814148-90f74ca9-cf9c-4635-8598-7396f7b21367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjc2NzYsIm5iZiI6MTczMDM2NzM3NiwicGF0aCI6Ii81MjY5NTAzNS8zODE4MTQxNDgtOTBmNzRjYTktY2Y5Yy00NjM1LTg1OTgtNzM5NmY3YjIxMzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA5MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWFjMGZjZWYyYzVkMjM2MDBjZjE4Zjg0M2U5MzA3YTBiYjRiZTRhYWE3YThmOTc0YjhmOGU3ZmZhMzE4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fCeS9jISDFtGCfNJVlgu4-oF_8KvyY7m6HC_2_hHhnU) 刚刚加入了视频推理的支持！为了保证代码简洁，方便修改，并没有对输出框进行美化。 你可以根据需要加粗边框、变更颜色等。

![image](https://github.com/user-attachments/assets/d1ef40ac-b2b1-44a5-ba8f-9ed38ef871d0)
为什么可视化的结果不是百分比呢？而是10.93呢？

**Comment by yaosx425** [comment]
> 类别1，置信度93%

好的谢谢您！
