### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by WtElio** [Peterande/D-FINE#16]
在训练阶段，第71轮评估完成后报错，有哪位大佬复现过程中碰到过类似情况吗？
![9a796696e05ae4526d6126c193e8526](https://github.com/user-attachments/assets/b32ab955-e849-49ab-8b38-d642165820e2)

**Comment by Peterande** [comment]
你可以检查以下你直接resume训练会不会报错，然后尝试debug~

**Comment by YOLODetector** [comment]
我也遇到这个问题了，有解决的吗
