### ISSUE TITLE
Could FDR and GOO-LSD use in ultralytics(yolov8 v10 11)？

### ISSUE THREAD

**Issue by taofuyu** [Peterande/D-FINE#17]
Thanks！

**Comment by Peterande** [comment]
Hi~I think you should ask ultralytics about this issue, because YOLO is not a layer-by-layer optimization prediction, so it requires further modification of the network architecture

**Comment by taofuyu** [comment]
So, FDR and GO-LSD can only be used in transformer-based detectors ?

**Comment by Peterande** [comment]
It has nothing to do with using transformer or CNN, it's a matter of YOLO architecture
