### ISSUE TITLE
TensorRT Dynamic shape

### ISSUE THREAD

**Issue by quangdungluong** [Peterande/D-FINE#18]
Hi, thanks for your advanced repository. I want to export the D-FINE model to TensorRT with dynamic batch size, but I encountered an error. Have you tried exporting to dynamic batch size, and how can I do it?

**Comment by Peterande** [comment]
Sorry😢I haven't tried it yet. I'll try in the near future. You can post the error message to see if anyone can help you.

**Comment by hongsamvo** [comment]
@quangdungluong Hi, I may got the same error. I got this error `[executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.` when I run input with batch size > 1. I tried to convert model to onnx again and add more dynamic axis (boxes, labels, scores) but this not fix problem. Did you find the solution?

**Comment by zxm97** [comment]
> [@quangdungluong](https://github.com/quangdungluong) Hi, I may got the same error. I got this error `[executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.` when I run input with batch size > 1. I tried to convert model to onnx again and add more dynamic axis (boxes, labels, scores) but this not fix problem. Did you find the solution?
modify export_onnx.py:
```
dynamic_axes = {
        "images": {
            0: "N",
        },
        "labels":{
            0: "N",
        },
        "boxes":{
            0: "N",
        },
        "scores":{
            0: "N",
        },
    }
```
export tensorrt with command:
`trtexec --onnx=model.onnx --saveEngine=model.engine --minShapes=images:1x3x640x640 --optShapes=images:8x3x640x640 --maxShapes=images:32x3x640x640 --fp16`

**Comment by edwardnguyen1705** [comment]
> n I

@zxm97 
That means you already successfully converted DFINE models to TRT with dynamic batch size?
