### ISSUE TITLE
训练到82个epoch 显存/内存溢出

### ISSUE THREAD

**Issue by Ruanlt** [Peterande/D-FINE#19]
在自有的数据上训练，测试了s和m，都是在第82的epoch的同一个位置报错。

![Snipaste_2024-11-01_16-41-42](https://github.com/user-attachments/assets/65eb6b7b-21d5-439a-aebe-7038ab772542)

![Snipaste_2024-11-01_16-42-04](https://github.com/user-attachments/assets/fab003f9-856a-4aee-8125-cf50e3e0b89f)

**Comment by Peterande** [comment]
根据日志，这并非代码错误，是服务器环境错误导致进程停止

**Comment by Ruanlt** [comment]
服务器环境错误？有更具体一些的方向吗？

报错的时候gpu显存正常，但是使用率都达到了100%，并且卡住一动不动。

**Comment by Peterande** [comment]
图示报错的可能性非常多，比如显存或者内存溢出以后，超过最长等待时间就会报这个错误，并不是真正的代码错误，所以我也没法判断原因

**Comment by ZJDATY** [comment]
@Peterande @Ruanlt    修改训练轮数是怎么改的，w我想把80轮改多点，不知道下面的72 改不改。怎么理解72+2n
![image](https://github.com/user-attachments/assets/97896fa2-d54d-43cb-9ac2-9e94e961fd0f)

**Comment by Peterande** [comment]
您截图的意思就是持续训练1582轮，然后最后8轮停掉部分数据增强，1600是用轮数，这是按照RT-DETRv2的训练策略指定的，具体可以看一下那篇论文中的介绍
