### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by hieulv3** [Peterande/D-FINE#2]
Thank you for your efforts,

![image](https://github.com/user-attachments/assets/84a60380-fd31-4e2d-9738-f18c840be3ca)

This issue occur when I train model with custom dataset. I did follow your guild

**Comment by Peterande** [comment]
It looks like you're trying to train a new dataset using the pretrained weights (and the classes less than both COCO and Objects365). Currently, the code logic maps the Objects365 classes to COCO during finetuning if the categories are different. If you want to map to your own custom classes, you can customize the self.obj365_ids. Also, I’ve just updated the code in src/solver/_solver.py. Now, the mismatched class heads will be automatically skipped. You can choose the appropriate solution based on your situation.

**Comment by hieulv3** [comment]
> It looks like you're trying to train a new dataset using the pretrained weights (and the classes less than both COCO and Objects365). Currently, the code logic maps the Objects365 classes to COCO during finetuning if the categories are different. If you want to map to your own custom classes, you can customize the self.obj365_ids. Also, I’ve just updated the code in src/solver/_solver.py. Now, the mismatched class heads will be automatically skipped. You can choose the appropriate solution based on your situation.
Thank you. Did these models support training huge image (img_size: 5300x3300)? I've got this error after fix the above error
![image](https://github.com/user-attachments/assets/fede6ce7-40fe-4dfb-b1a0-d23f939c5580)

**Comment by Peterande** [comment]
**It seems that this issue is related to the PIL library rather than the model itself.** 

During training, the model randomly resizes all images to a range of 400x400 to 800x800 to improve generalization. However, during inference, as long as there is enough GPU memory, there are no specific size restrictions. The problem arises from PIL's limitations on image sizes, and is clearly written in the Error Log.

I recommend checking the script located at tools/dataset/resize_obj365.py for preprocessing large images. This script can help you resize the images before training to avoid the decompression bomb error.

**Comment by hieulv3** [comment]
> **It seems that this issue is related to the PIL library rather than the model itself.**
> 
> During training, the model randomly resizes all images to a range of 400x400 to 800x800 to improve generalization. However, during inference, as long as there is enough GPU memory, there are no specific size restrictions. The problem arises from PIL's limitations on image sizes, and is clearly written in the Error Log.
> 
> I recommend checking the script located at tools/dataset/resize_obj365.py for preprocessing large images. This script can help you resize the images before training to avoid the decompression bomb error.


Yes. This issue is related to PIL. So I added `MAX_IMAGE_PIXELS = None` in the function `_decompression_bomb_check` of PIL.Image to bypass this error. Thank you and have a nice day

**Comment by Peterande** [comment]
You're welcome. Have a nice day~

**Comment by Peterande** [comment]
Optional Custom Finetune Tutorial is added: eed6df6132098791c03c5c07d50fa84c415a7b7b
