### ISSUE TITLE
received 0 items of ancdata

### ISSUE THREAD

**Issue by FlyFireF** [Peterande/D-FINE#22]
![6SJ6J1~W1C80_A)IAWKXU 3](https://github.com/user-attachments/assets/47466698-0403-4634-b0df-1522b05b6a90)
如图，在模型的评估阶段报这样的错误，网上查说是打开文件过多，但是调了ulimit为65536，以及在配置文件中将num_workers改成1还是不行.
I've got this error during the validation, I searched the internet and got "files opend too much", but it still cannot work well after I set 'ulimit' to 65536 and changed 'num_workers' to 1 in the config file.

**Comment by Peterande** [comment]
You can try adding `torch.multiprocessing.set_sharing_strategy('file_system')` or set num_workers to 0

**Comment by FlyFireF** [comment]
> You can try adding `torch.multiprocessing.set_sharing_strategy('file_system')` or set num_workers to 0

I've tried adding `torch.multiprocessing.set_sharing_strategy('file_system')` and the problem was solved! Thank you very much!
