### ISSUE TITLE
CPU跑满 和GPU偷懒

### ISSUE THREAD

**Issue by ZJDATY** [Peterande/D-FINE#23]
![image](https://github.com/user-attachments/assets/4ef3aee1-f7f1-4754-8ef0-8d54f6a32fb3)
我跑的原始图片大小是1280x1024 .   resize什么的都是默认设置 应该都是640 640
按照教程和Issues里的一些问题，设置了这些参数，其他都默认
![image](https://github.com/user-attachments/assets/a0dbf4bc-c079-41c7-bd84-5ccb75e8b864)
https://github.com/Peterande/D-FINE/issues/13#issuecomment-2446879522
https://github.com/Peterande/D-FINE/issues/5#issuecomment-2428200244

`total_batch_size:16`

`num_classes: 1`

还有个问题 跑出来这个曲线 看起来也太诡异了啊 起伏这么大的吗 是不是哪边参数设置错了

![image](https://github.com/user-attachments/assets/6f927edd-94f2-4554-bbe9-8378c1abf70b)

**Comment by Peterande** [comment]
GPU没有跑满应该是CPU的性能受限，GPU一直在等待CPU读取和处理数据，你可以考虑提前resize数据集。关于性能起伏这么大的问题，我在其他数据集上没有发现过类似情况，就算是数据量特别小的数据集也不会起伏这么明显，你可以用训练好的权重运行一下可视化代码，检查一下是不是标签错位了之类的原因。

**Comment by ZJDATY** [comment]
@Peterande  我感觉 还是得想办法优化一下，CPU占用高，GPU低的问题。我现在把预处理操作都暂时注释了，图片也提前resize了，CPU占用还是 很高，GPU也才从5增加到30的负载，我的CPU性能应该不低了，还是高占用，GPU跑不起来，我查了一下CPU的调度。我截图了2张，有能力优化的，可以想办法来优化一下。
![image](https://github.com/user-attachments/assets/041b3db1-a0eb-4a5a-9aae-8989eefdae64)
![image](https://github.com/user-attachments/assets/d0e3ae29-bf7f-4243-aa5c-ec64c6a8f184)

**Comment by Peterande** [comment]
很抱歉，但是在我们的平台上，包括各种平台和各种GPU、CPU组合下，都没有遇到类似的问题，我查看了当时的GPU利用率，都很正常没有波动

**Comment by ZJDATY** [comment]
![profile](https://github.com/user-attachments/assets/f2a9f00d-70a1-48fa-b3de-1ba1765a3cc8)

**Comment by Peterande** [comment]
请问torch有更新到最新版试过吗？

**Comment by ZJDATY** [comment]
> 请问torch有更新到最新版试过吗？

我是从2.4.1 降下来的 降到了2.2.2

**Comment by ZJDATY** [comment]
@Peterande  从火焰图上看 下面这几个函数 是性能的瓶颈，如果可以优化 将极大改善CPU占用。
![屏幕截图 2024-11-02 223426](https://github.com/user-attachments/assets/e94aae2d-02d1-4542-900a-1ea41d439767)
![屏幕截图 2024-11-02 223414](https://github.com/user-attachments/assets/40d5db2e-b7a6-484a-a6b9-f47713c2d3d5)
![屏幕截图 2024-11-02 223404](https://github.com/user-attachments/assets/a04a6448-22a3-4c4f-b171-d12e43eb0b11)

**Comment by Peterande** [comment]
py-spy很多时候是不准的，我们根据之前开源的经验来看，平台I/O优化后，速度快了很多倍。但是py-spy的火焰图前后完全一致。并且我在A800, 4090, 3090, titanxp上训练速度都是非常正常的。我个人还是更倾向于您换个设备先试一试，而不是肯定一定是代码优化问题

**Comment by Peterande** [comment]
截图的三个代码除了PIL的图片读取，基本都和CPU基本无关

**Comment by ZJDATY** [comment]
也许吧 可能还是yolo的生态做的太好了，维护的人比较多，跑那个还没遇到CPU吃满，GPU负载不佳的情况。我在我两台windows系统上都遇到这个情况，我还有一个ubuntu系统，它上面没空间了，所以暂时还没办法试。

**Comment by Peterande** [comment]
我后续会找机会在windows系统上尝试一下，如果您近期实在解决不了，也可以尝试改变一下num_workers和batchsize的组合，找到一个平衡点。

**Comment by super-song-sir** [comment]
> 我后续会找机会在windows系统上尝试一下，如果您近期实在解决不了，也可以尝试改变一下num_workers和batchsize的组合，找到一个平衡点。

请求出一个window运行教程，目前总是会出现RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
