### ISSUE TITLE
Using a video to infer met "size mismatch"

### ISSUE THREAD

**Issue by FlyFireF** [Peterande/D-FINE#25]
![image](https://github.com/user-attachments/assets/5335b355-1b18-4078-91c5-7201ebca47d3)
我使用图片数据训练，现使用视频来进行推理，但是报错如图。想知道这个模型是否支持比例自动缩放。或者如何手动添加这一功能，再或者是否可以把视频通过剪辑软件改变高宽比来解决这一问题。
I used image data to train the model, and used a video to infer, but there was an error shown in the screenshot. I wonder if this model supports auto-resizing, or how can I add this feature manually, or whether changing the size of the video via video editing software will solve the problem.

**Comment by Peterande** [comment]
推理的输入宽高比是任意的，不用任何额外操作。看报错应该是指定错config文件了，请确保训练推理用的是相同的config。
The input aspect ratio for inference is arbitrary without any additional operations. Judging from the error message, it should be that the config file was specified incorrectly. Please ensure that the same config is used for training and inference.

**Comment by Peterande** [comment]
具体来说，你的训练用的是16类，但是推理用的是自定义数据集config中默认的777类。
Specifically, you used 16 classes for training, but 777 classes by default in custom dataset config for inference.

**Comment by FlyFireF** [comment]
> 具体来说，你的训练用的是16类，但是推理用的是自定义数据集config中默认的777类。 Specifically, you used 16 classes for training, but 777 classes by default in custom dataset config for inference.

噢！我更新了一次项目文件，配置文件被覆盖了。不过更改过来之后，报错 size mismatch for decoder.anchors: copying a param with shape torch.Size([1, 2100, 4]) from checkpoint, the shape in current model is torch.Size([1, 8400, 4]). 我不知道这个2100和8400是来自哪里的。

**Comment by Peterande** [comment]
这个是backbone输出的特征图尺寸，默认是三个尺度80*80+40*40+20*20=8400，你训练的时候是否修改了输入尺寸或者其他的什么参数

**Comment by FlyFireF** [comment]
> 这个是backbone输出的特征图尺寸，默认是三个尺度80_80+40_40+20*20=8400，你训练的时候是否修改了输入尺寸或者其他的什么参数

我将配置文件都还原为更新前的，成功运行了，感谢您的耐心解答！

**Comment by Peterande** [comment]
不客气～感谢支持
