### ISSUE TITLE
您好 请问windows上如何训练呢 还有这个模型训练最少需要多大显存呢

### ISSUE THREAD

**Issue by xhfxhf** [Peterande/D-FINE#26]

**Comment by Peterande** [comment]
Windows我们暂时没有训练过，但有其他issue成功训练过，具体可以参考一下anaconda环境的配置和类似网络（如RT-DETR）网络上的训练教程。显存大小是根据设置的 batch size 数目来的，不是固定的，教程中有缩放 batch size 时其他超参的放缩教程，可以参考。

**Comment by Kaze816** [comment]
Windowsg下，total_batch_size: 8  约需要11.5G @xhfxhf 
我是单卡，屏蔽了相关分布的训练代码

**Comment by SDIX-7** [comment]
我也屏蔽了相关分布的训练代码，使用该训练命令 4060ti-16g
 ` python train.py -c configs/dfine/custom/dfine_hgnetv2_n_custom.yml --use-amp --seed=0 `
训练速度很慢，其GPU使用率和功耗均不高，使用自己的数据，总共800张图片 0.8:0.2划分训练集和验证集。
Initial lr: [0.0001, 0.0001, 0.0002, 0.0002]
building train_dataloader with batch_size=32...
building val_dataloader with batch_size=64...

![Image](https://github.com/user-attachments/assets/94fcb287-7370-49b2-a550-3e60b9076c8b)

![Image](https://github.com/user-attachments/assets/d5d409bd-2323-4b40-b29f-d02f72bb4955)
可能是我哪里屏蔽错了
