### ISSUE TITLE
自建数据集指标差可能是什么原因

### ISSUE THREAD

**Issue by linzezuo** [Peterande/D-FINE#29]
你好，我的自建数据集用yolov8可以训练出不错的效果，但我转换数据格式后用预训练好的DFINE-s微调的效果很差，可以帮忙分析下原因吗
1.标签转换有问题？
2.epoch数太少？
<img width="779" alt="1730713060761" src="https://github.com/user-attachments/assets/5427a03e-aee7-46e8-9037-cca845736cf1">

**Comment by Peterande** [comment]
性能有点过于低了，可能是标签没对齐，你可以参考教程可视化最后的检测结果看看问题出在哪。

**Comment by lswgh** [comment]
请问是标签的问题吗，如果不是的话，最后是怎么解决的呢

**Comment by S130111** [comment]
我有同样的问题，请问解决了吗
