### ISSUE TITLE
bounding box assertion

### ISSUE THREAD

**Issue by kennyvoo** [Peterande/D-FINE#3]
```
[rank0]:   File "/home/kenny/D-FINE/src/zoo/dfine/box_ops.py", line 54, in generalized_box_iou          
[rank0]:     assert (boxes1[:, 2:] >= boxes1[:, :2]).all()   

```
Great work! After training on the CrowdHuman dataset for several epochs, I encountered an assertion error. I've attached the training logs for reference. Could you please help me understand what might have gone wrong?

[training_log.txt](https://github.com/user-attachments/files/17456759/training_log.txt)
[log.txt](https://github.com/user-attachments/files/17456761/log.txt)

**Comment by Peterande** [comment]
It seems you are using the Objects365-pretrained D-FINE-S, fine-tuning on another dataset, and encountered NaN issues after several epochs. This didn’t happen during COCO fine-tuning. There could be many potential causes for this problem. I'm happy to suggest a few solutions:

1. Use `bash reference/safe_training.sh`. This might help avoid NaN issues caused by unexpected data distribution problems.
2. You can try commenting out lines L54 and L55 in `D-FINE/src/zoo/dfine/box_ops.py`:
    ```python
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
    assert (boxes2[:, 2:] >= boxes2[:, :2]).all()
    ```
    Then continue to reproduce the actual NaN error. The next time the network outputs NaN, a `NaN.pth` file will be saved in the path, which you can use to debug and find the real issue.

**Comment by Peterande** [comment]
If you need further assistance to completely resolve the issue, perhaps you could provide a minimal reproducible demo.

**Comment by coderRicardo** [comment]
> Could
I have the same question. Have you solved it? How did you solve it? Looking forward to your answer. Thank you very much

**Comment by Peterande** [comment]
> > Could
> > I have the same question. Have you solved it? How did you solve it? Looking forward to your answer. Thank you very much

Under what setting did you encounter this problem? Do you have training logs?

**Comment by coderRicardo** [comment]
I want to finetune on my custom dataset using the obj365 model, but I keep getting the following error:
<img width="971" alt="image" src="https://github.com/user-attachments/assets/94d4e82b-e9c9-4136-a89e-e736bf9ab2e8">
[train.log](https://github.com/user-attachments/files/17539989/train.log)

**Comment by Peterande** [comment]
> I want to finetune on my custom dataset using the obj365 model, but I keep getting the following error: <img alt="image" width="971" src="https://private-user-images.githubusercontent.com/101027724/380644364-94d4e82b-e9c9-4136-a89e-e736bf9ab2e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDgxODIsIm5iZiI6MTczMDEwNzg4MiwicGF0aCI6Ii8xMDEwMjc3MjQvMzgwNjQ0MzY0LTk0ZDRlODJiLWU5YzktNDEzNi1hODllLWU3MzZiZjlhYjJlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwOTMxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGE3NDMxYjc1ZDE3M2NiMThjZDU4Y2I1M2U5Y2JhZTdmNTEyZTc1YTZhNDNiNmY2ZTcxOGQ1Yzc2NDA4MDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NgWMG640Mtxw5fPI3G7Wav0SFp0-FBc1TpKU0bz6K7c"> [train.log](https://github.com/user-attachments/files/17539989/train.log)

It can be seen from your training log that the problem you encountered is different from that of the person in the first question. He encountered the problem after several steps. This situation usually indicates the occurrence of NaN during training. However, you encountered this problem from the very beginning. Please carefully check whether the number of classes has been set correctly. You can try adding 1 to `num_classes` and see if it works.
