### ISSUE TITLE
tensort推理失败，请问是什么原因

### ISSUE THREAD

**Issue by kongxm889** [Peterande/D-FINE#32]
通过onnx导出engine文件，命令如下：
![image](https://github.com/user-attachments/assets/47e26536-5faa-423b-b120-099071e98641)
所使用的onnx输入输出如下，使用onnx_inf.py推理无问题，
![image](https://github.com/user-attachments/assets/941dbd33-19ef-467b-9eea-e12b9510b0fe)
。但是使用trt_inf.py推理engine文件无结果：请问是我导出的onnx有问题还是导出的engine有问题，还是其他问题呢？

**Comment by migsdigs** [comment]
Hi! Were you able to get the tft_inf example to work? I also have no result, just the input without any shown detections. Thank you
