### ISSUE TITLE
Are there any plans to release the COCO pre-trained model for D-FINE-N?

### ISSUE THREAD

**Issue by tatsuya-fukuoka** [Peterande/D-FINE#34]
The dfine_hgnetv2_n_coco.yml has been added, but are there any plans to release the COCO pre-trained models for D-FINE-N?
[dfine_hgnetv2_n_coco.yml]
https://github.com/Peterande/D-FINE/blob/master/configs/dfine/dfine_hgnetv2_n_coco.yml

Best regards.

**Comment by Peterande** [comment]
Yeah, training~

**Comment by tatsuya-fukuoka** [comment]
Thank you for releasing the COCO pre-trained models for D-FINE-N.
https://github.com/Peterande/D-FINE

 I started fine tuning immediately.

Thank you!

**Comment by Peterande** [comment]
You're welcome~

**Comment by Wulingtian** [comment]
> Yeah, training~
object365的D-FINE-N模型有在训练吗？

**Comment by Peterande** [comment]
> > Yeah, training~
> > object365的D-FINE-N模型有在训练吗？

在训练，但由于之前的卡让给组里其他赶会的同学了，所以在见缝插针训练中，时间不确定😊
