### ISSUE TITLE
训练新的类别

### ISSUE THREAD

**Issue by HandsLing** [Peterande/D-FINE#40]
请问我要如何训练既不在obj365也不在coco数据集里面的类别呢

**Comment by Peterande** [comment]
https://github.com/Peterande/D-FINE/blob/9f8c2b430f6e9d40aac966b79984cc2c9f88f39b/src/solver/_solver.py#L181

什么都不改，或者注释掉这一行。两种方法应该都可以

**Comment by HandsLing** [comment]
说错了 是微调 不是训练 基于obj365预训练的模型咋微调呢

**Comment by HandsLing** [comment]
请问一下 为啥我训练自己的数据 验证集上ap一直是0啊

**Comment by shaoyandea** [comment]
> 请问一下 为啥我训练自己的数据 验证集上ap一直是0啊

我也遇到了这个问题，查找发现，模型输出的box是归一化后的位置，而target的box是在原图上的未归一化的坐标且坐标值范围超出了模型输入图像的大小，说明数据处理的增广过程部分增广对box做了错误的变换，我就将和图像位置变换有关的增广去除，只保留对图像做变换但是box不受影响的增广，再训练在第一个epoch验证时metric指标就正常了

**Comment by Donaghys** [comment]
> 请问一下 为啥我训练自己的数据 验证集上ap一直是0啊这个问题你解决了吗？
