### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in该怎么解决呢 

### ISSUE THREAD

**Issue by hubing-2** [Peterande/D-FINE#41]

**Comment by Peterande** [comment]
这与本repo无关，是环境的问题，请google一下~

**Comment by hubing-2** [comment]
最开始时训练报错说是要初始化进程，在网上搜了搜解决方法，加上了
os.environ['MASTER_ADDR'] = 'localhost'             
os.environ['MASTER_PORT'] = '12345'                 
torch.distributed.init_process_group(backend='NCCL',init_method='env://', world_size=1, rank=0)
这三行代码，之后又出现了RuntimeError: Distributed package doesn't have NCCL built in

**Comment by hubing-2** [comment]
我Google一下

**Comment by Peterande** [comment]
建议升级一下所有的依赖，别用以前的环境
