### ISSUE TITLE
tensorrt 转fp16精度严重下降

### ISSUE THREAD

**Issue by kongxm889** [Peterande/D-FINE#44]
转engine文件如果加上--fp16转出来的engine在检测上精度下降非常多，大概会比正常检测漏检至少一半以上，无论是C++版还是python版我都试了，都是一样的问题。如果以fp32精度转engine文件进行检测，精测效果和检测时间同onnxruntime-gpu时间差不多。请问为什么转-fp16精度会下降那么多呢。

**Comment by Peterande** [comment]
https://github.com/lyuwenyu/RT-DETR/issues/104

可以根据这个讨论检查一下。您是重新训练了模型吗？我之前自己写了TensorRT的COCO_eval相关代码。没有观察到任何accuracy drop，之后我才开始进行大规模训练。按理说应该是没有问题的。

**Comment by Peterande** [comment]
可以观察一下转TensorRT过程中的所有warning。并保证相关的包都升级到了最新版本

**Comment by Peterande** [comment]
补充一下，之前我在安培架构和非安培架构的GPU进行测试，确实出现过出入。这是TensorRT的问题，你可以尝试编译的时候加上 --noTF32

**Comment by kongxm889** [comment]
> 补充一下，之前我在安培架构和非安培架构的GPU进行测试，确实出现过出入。这是TensorRT默认打开了 TF32 的问题，TF32格式是安培架构显卡Tensor Core中新增的一种NV自定义的非标数据类型。你可以尝试编译的时候加上 --noTF32 ,不过这也许会影响速度。



> [lyuwenyu/RT-DETR#104](https://github.com/lyuwenyu/RT-DETR/issues/104)
> 
> 可以根据这个讨论检查一下。您是重新训练了模型吗？我之前自己写了TensorRT的COCO_eval相关代码。没有观察到任何accuracy drop，之后我才开始进行大规模训练。按理说应该是没有问题的。

是的，我自己训练的自己的数据集，我查了一些资料看到别人用RT-DETR模型部署engine模型也遇到了一样的问题。

**Comment by kongxm889** [comment]
> 补充一下，之前我在安培架构和非安培架构的GPU进行测试，确实出现过出入。这是TensorRT默认打开了 TF32 的问题，TF32格式是安培架构显卡Tensor Core中新增的一种NV自定义的非标数据类型。你可以尝试编译的时候加上 --noTF32 ,不过这也许会影响速度。

好的，我再尝试一下

**Comment by Yshelgi** [comment]
我也遇到了这种情况，使用obj2coco的预训练权重转为onnx后，利用`trtexec`转为engine时，如果设置了`--fp16`,在给出的`trt_inf.py`上会出现labels和scores异常的问题(labels全为0，scores全部为0.0011），如下图
![image](https://github.com/user-attachments/assets/88008e8f-c8bb-4637-8725-a7d9cea6b7ca)

当我取消设置`--fp16`重新生成engine后，一切正常。考虑是不是topk部分，如果fp16会导致后续出错？

**Comment by Peterande** [comment]
已确认。是GPU是否是安培架构的问题：

3090 TRT FP16:

![image](https://github.com/user-attachments/assets/cde67e5e-dc28-4041-bf80-b24d5c072669)

4090 TRT FP16:

![image](https://github.com/user-attachments/assets/6ebe2e74-feb9-4ffb-a09e-4755544724fe)

**Comment by zodiac50** [comment]
> 我也遇到了这种情况，使用obj2coco的预训练权重转为onnx后，利用`trtexec`转为engine时，如果设置了`--fp16`,在给出的`trt_inf.py`上会出现labels和scores异常的问题(labels全为0，scores全部为0.0011），如下图 ![image](https://private-user-images.githubusercontent.com/50126188/384872676-88008e8f-c8bb-4637-8725-a7d9cea6b7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODkxNzcsIm5iZiI6MTczMTM4ODg3NywicGF0aCI6Ii81MDEyNjE4OC8zODQ4NzI2NzYtODgwMDhlOGYtYzhiYi00NjM3LTg3MjUtYTdkOWNlYTZiN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZGNmYzA4NGE1Mjg0OTE1OWQ2MWYwYTAxZjc3MWNkYzBjY2M3OGFiM2ZkN2U3NzIzZjRmMTI1NGVkZDNmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wZUkK9gGAtMMMn0d9KWNH1r_P-dyCKt_nvmEAOVNDA)
> 
> 当我取消设置`--fp16`重新生成engine后，一切正常。考虑是不是topk部分，如果fp16会导致后续出错？

你好你这边转换onnx是通过的么，为什么我这边用export转换会报错

**Comment by Yshelgi** [comment]
> > 我也遇到了这种情况，使用obj2coco的预训练权重转为onnx后，利用`trtexec`转为engine时，如果设置了`--fp16`,在给出的`trt_inf.py`上会出现labels和scores异常的问题(labels全为0，scores全部为0.0011），如下图 ![image](https://private-user-images.githubusercontent.com/50126188/384872676-88008e8f-c8bb-4637-8725-a7d9cea6b7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODkxNzcsIm5iZiI6MTczMTM4ODg3NywicGF0aCI6Ii81MDEyNjE4OC8zODQ4NzI2NzYtODgwMDhlOGYtYzhiYi00NjM3LTg3MjUtYTdkOWNlYTZiN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZGNmYzA4NGE1Mjg0OTE1OWQ2MWYwYTAxZjc3MWNkYzBjY2M3OGFiM2ZkN2U3NzIzZjRmMTI1NGVkZDNmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wZUkK9gGAtMMMn0d9KWNH1r_P-dyCKt_nvmEAOVNDA)
> > 当我取消设置`--fp16`重新生成engine后，一切正常。考虑是不是topk部分，如果fp16会导致后续出错？
> 
> 你好你这边转换onnx是通过的么，为什么我这边用export转换会报错

检查pytorch、onnx相关的版本，另外最好贴一下报错截图，不然不好帮你分析

**Comment by zodiac50** [comment]
> > > 我也遇到了这种情况，使用obj2coco的预训练权重转为onnx后，利用`trtexec`转为engine时，如果设置了`--fp16`,在给出的`trt_inf.py`上会出现labels和scores异常的问题(labels全为0，scores全部为0.0011），如下图 ![image](https://private-user-images.githubusercontent.com/50126188/384872676-88008e8f-c8bb-4637-8725-a7d9cea6b7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODkxNzcsIm5iZiI6MTczMTM4ODg3NywicGF0aCI6Ii81MDEyNjE4OC8zODQ4NzI2NzYtODgwMDhlOGYtYzhiYi00NjM3LTg3MjUtYTdkOWNlYTZiN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZGNmYzA4NGE1Mjg0OTE1OWQ2MWYwYTAxZjc3MWNkYzBjY2M3OGFiM2ZkN2U3NzIzZjRmMTI1NGVkZDNmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wZUkK9gGAtMMMn0d9KWNH1r_P-dyCKt_nvmEAOVNDA)
> > > 当我取消设置`--fp16`重新生成engine后，一切正常。考虑是不是topk部分，如果fp16会导致后续出错？
> > 
> > 
> > 你好你这边转换onnx是通过的么，为什么我这边用export转换会报错
> 
> 检查pytorch、onnx相关的版本，另外最好贴一下报错截图，不然不好帮你分析

![image](https://github.com/user-attachments/assets/afb610eb-d338-4999-9577-dd082afb476d)
这个是我转换时候的报错，大佬说要convert_to_deploy()下，看了下没找到具体位置

**Comment by zodiac50** [comment]
https://github.com/Peterande/D-FINE/issues/13#issuecomment-2451137549，已解决，感谢各位大佬，需要用222版本的torch，pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

**Comment by Yshelgi** [comment]
> > > > 我也遇到了这种情况，使用obj2coco的预训练权重转为onnx后，利用`trtexec`转为engine时，如果设置了`--fp16`,在给出的`trt_inf.py`上会出现labels和scores异常的问题(labels全为0，scores全部为0.0011），如下图 ![image](https://private-user-images.githubusercontent.com/50126188/384872676-88008e8f-c8bb-4637-8725-a7d9cea6b7ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODkxNzcsIm5iZiI6MTczMTM4ODg3NywicGF0aCI6Ii81MDEyNjE4OC8zODQ4NzI2NzYtODgwMDhlOGYtYzhiYi00NjM3LTg3MjUtYTdkOWNlYTZiN2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MjExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZGNmYzA4NGE1Mjg0OTE1OWQ2MWYwYTAxZjc3MWNkYzBjY2M3OGFiM2ZkN2U3NzIzZjRmMTI1NGVkZDNmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3wZUkK9gGAtMMMn0d9KWNH1r_P-dyCKt_nvmEAOVNDA)
> > > > 当我取消设置`--fp16`重新生成engine后，一切正常。考虑是不是topk部分，如果fp16会导致后续出错？
> > > 
> > > 
> > > 你好你这边转换onnx是通过的么，为什么我这边用export转换会报错
> > 
> > 
> > 检查pytorch、onnx相关的版本，另外最好贴一下报错截图，不然不好帮你分析
> 
> ![image](https://private-user-images.githubusercontent.com/152422276/385155980-afb610eb-d338-4999-9577-dd082afb476d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTI1MDYsIm5iZiI6MTczMTM5MjIwNiwicGF0aCI6Ii8xNTI0MjIyNzYvMzg1MTU1OTgwLWFmYjYxMGViLWQzMzgtNDk5OS05NTc3LWRkMDgyYWZiNDc2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwNjE2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWIzMzg0YWVmNzkzZTIzOTNmMGM1NmQ0MjUwZWQwMjM5YzZjYmMwMDIxMTYzYWY1YmUyYmFlMjEwMzgzZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9bmWoxBvpczMFMFZI8dBzALoIH2TcHEegI3X8FQBWqU) 这个是我转换时候的报错，大佬说要convert_to_deploy()下，看了下没找到具体位置

更新相关库的版本试试，pad应该是支持的

**Comment by zodiac50** [comment]
已解决，torch的版本问题，感谢大佬！

**Comment by kongxm889** [comment]
> 已解决，torch的版本问题，感谢大佬！

我试了不同版本的torch还有你说的这个，还是不行，我不确定别人是不是都也可以了

**Comment by kongxm889** [comment]
> 已解决，torch的版本问题，感谢大佬！

我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决了这个问题

**Comment by JunerLee** [comment]
> > 已解决，torch的版本问题，感谢大佬！
> 
> 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> 
> python： import tensorrt as trt
> 
> for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT

非常感谢@kongxm889 ，也遇到了同样的问题，直接trtexe转成engine，加上--fp16精度损失严重，去掉后就没问题但是就没有加速了, 楼主可以提供一下onnx转engien的python或者c++  完整代码吗？

**Comment by lazyfan** [comment]
> > 已解决，torch的版本问题，感谢大佬！
> 
> 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> 
> python： import tensorrt as trt
> 
> for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT

我按照你说的保持归一化层为FP32精度，其他层使用FP16，但是还是存在结果不对的问题，还有别的细节吗，如果有转换代码提供更好，谢谢大佬！

**Comment by ronghuaiyang** [comment]
> > 已解决，torch的版本问题，感谢大佬！
> 
> 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> 
> python： import tensorrt as trt
> 
> for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT

感谢大佬！
我也是用该方法解决的这个问题，只是相比全部用fp16精度，速度会慢不少，不知道有没有得到和fp16同样速度的方法

**Comment by JunerLee** [comment]
> > > 已解决，torch的版本问题，感谢大佬！
> > 
> > 
> > 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> > python： import tensorrt as trt
> > for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT
> 
> 感谢大佬！ 我也是用该方法解决的这个问题，只是相比全部用fp16精度，速度会慢不少，不知道有没有得到和fp16同样速度的方法

大佬可以提供一下你的完整源码吗，我按照这个来好像也不行，感谢@ronghuaiyang

**Comment by ronghuaiyang** [comment]
> > > > 已解决，torch的版本问题，感谢大佬！
> > > 
> > > 
> > > 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> > > python： import tensorrt as trt
> > > for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT
> > 
> > 
> > 感谢大佬！ 我也是用该方法解决的这个问题，只是相比全部用fp16精度，速度会慢不少，不知道有没有得到和fp16同样速度的方法
> 
> 大佬可以提供一下你的完整源码吗，我按照这个来好像也不行，感谢@ronghuaiyang



        for i in range(self.network.num_layers):
            layer = self.network.get_layer(i)
            if layer.type == trt.LayerType.NORMALIZATION:
                layer.precision = trt.DataType.FLOAT

        with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
            log.info("Serializing engine to file: {:}".format(engine_path))
            f.write(engine.serialize())

就是在生成engin之前加上这个

**Comment by Yshelgi** [comment]
> > > > > 已解决，torch的版本问题，感谢大佬！
> > > > 
> > > > 
> > > > 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> > > > python： import tensorrt as trt
> > > > for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT
> > > 
> > > 
> > > 感谢大佬！ 我也是用该方法解决的这个问题，只是相比全部用fp16精度，速度会慢不少，不知道有没有得到和fp16同样速度的方法
> > 
> > 
> > 大佬可以提供一下你的完整源码吗，我按照这个来好像也不行，感谢@ronghuaiyang
> 
> ```
>     for i in range(self.network.num_layers):
>         layer = self.network.get_layer(i)
>         if layer.type == trt.LayerType.NORMALIZATION:
>             layer.precision = trt.DataType.FLOAT
> 
>     with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
>         log.info("Serializing engine to file: {:}".format(engine_path))
>         f.write(engine.serialize())
> ```
> 
> 就是在生成engin之前加上这个

我今天用coco_n试了一下，如果用`opset=17`导出再`--fp16`，貌似tensorrt推理精度没啥问题了

**Comment by ronghuaiyang** [comment]
> > > > > > 已解决，torch的版本问题，感谢大佬！
> > > > > 
> > > > > 
> > > > > 我尝试了更换torch版本，没有解决这个问题，不知道其他小伙伴有没有使用你的方法解决这个问题。 我是在onnx转engien文件的时候使得“归一化”层保持fp32位精度，其他层是fp16精度，解决的这个问题。相比之前全部是fp32速度提示不少，精度基本没损失，具体精度下降情况可以根据自己的数据集自己对比量化。其中我设置设精度的代码如下，供参考： C++： for (int i = 0; i < network->getNbLayers(); ++i) { nvinfer1::ILayer* layer = network->getLayer(i); if (layer->getType() == nvinfer1::LayerType::kNORMALIZATION) { layer->setPrecision(nvinfer1::DataType::kFLOAT); } }
> > > > > python： import tensorrt as trt
> > > > > for i in range(network.num_layers): layer = network.get_layer(i) if layer.type == trt.LayerType.NORMALIZATION: layer.precision = trt.DataType.FLOAT
> > > > 
> > > > 
> > > > 感谢大佬！ 我也是用该方法解决的这个问题，只是相比全部用fp16精度，速度会慢不少，不知道有没有得到和fp16同样速度的方法
> > > 
> > > 
> > > 大佬可以提供一下你的完整源码吗，我按照这个来好像也不行，感谢@ronghuaiyang
> > 
> > 
> > ```
> >     for i in range(self.network.num_layers):
> >         layer = self.network.get_layer(i)
> >         if layer.type == trt.LayerType.NORMALIZATION:
> >             layer.precision = trt.DataType.FLOAT
> > 
> >     with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
> >         log.info("Serializing engine to file: {:}".format(engine_path))
> >         f.write(engine.serialize())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就是在生成engin之前加上这个
> 
> 我今天用coco_n试了一下，如果用`opset=17`导出再`--fp16`，貌似tensorrt推理精度没啥问题了

不用将NORMALIZATION层设置成fp32了吗？
