### ISSUE TITLE
Can not convert to onnx. 

### ISSUE THREAD

**Issue by zodiac50** [Peterande/D-FINE#45]
torch.onnx.export转换时出现不支持的pooling

**Comment by zodiac50** [comment]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/b7e77e72-ed12-4219-87d5-1ba9ecc42b36">

**Comment by zodiac50** [comment]
sorry my mistake, unsupport get_pool_ceil_padding, not pool.

**Comment by Peterande** [comment]
You can use adaptive Pool2d layers. Remember to write a convert_to_deploy function to convert them to static Pool layers before deploy:
![Screenshot_20241111_112422](https://github.com/user-attachments/assets/fea41cde-c9bf-499f-bff0-8ddef3745021)

**Comment by zodiac50** [comment]
Thank ! but which file i should add this convert_to_deploy function above? I was failed to find it in error lines above.

**Comment by zodiac50** [comment]
pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118，已解决，需要torch222版本
