### ISSUE TITLE
Error running onnx inference with multiple images: "onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running GatherElements node. Name:'/model/decoder/GatherElements' Status Message: GatherElements op: 'indices' shape should have values within bounds of 'data' shape. Invalid value in indices shape is: 2""

### ISSUE THREAD

**Issue by igalve1998** [Peterande/D-FINE#50]
If I try to run onnx inference for multiple images at the same type I've got the error:

```onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running GatherElements node. Name:'/model/decoder/GatherElements' Status Message: GatherElements op: 'indices' shape should have values within bounds of 'data' shape. Invalid value in indices shape is: 2```

The inputs shape are the following:
 - **images** (im_data): (4, 3, 640, 640)
 - **orig_target_sizes** (orig_shape): (4, 2)

The python code is as follows:
```
output = dfine_session.run(
            output_names=None,
            input_feed={'images': im_data, "orig_target_sizes": orig_shape}
        )
```

Is there a way to run inference on múltiple images as one batch?

**Comment by igalve1998** [comment]
I think that I found the problem @Peterande . In the export onnx script you should change:

data = torch.rand(1, 3, 640, 640)
size = torch.tensor([[640, 640]])

for:

data = torch.rand(2, 3, 640, 640)
size = torch.tensor([[640, 640], [640, 640]])


Otherwise the exported model doesn't support batching. If I'm right I would like to make the PR myself to be a contributor if possible.

**Comment by Peterande** [comment]
https://github.com/Peterande/D-FINE/pull/35
👀
