### ISSUE TITLE
How compare validation metrics of D-Fine and Yolo11 on the same custom dataset?

### ISSUE THREAD

**Issue by ai8049520** [Peterande/D-FINE#53]
Hi!

Your D-fine project is great, thank you! My question  is how can I compare results of training yolo11s and D-fine custom model s? I attached output  from yolo11 monitor training and from D-fine model. Which metrics can I compare?
 Or there is some other way to compare them?
![Screenshot from 2024-11-12 21-28-39](https://github.com/user-attachments/assets/834417af-5c84-4791-8ea8-94b60de3301c)
![Screenshot from 2024-11-12 21-32-28](https://github.com/user-attachments/assets/892d53bf-ee7b-4a1f-9d07-9798ccea84c5)

**Comment by MiXaiLL76** [comment]
The yolo metrics are slightly overestimated relative to pycocotools \ faster-coco-eval validation.
For a more accurate comparison, it is necessary to validate the model using the same metrics. It is possible to convert the yolo prediction to coco format

**Comment by ai8049520** [comment]
Thank you! 
I get metrics like as for D-FINE for yolo11, using https://nbviewer.org/github/MiXaiLL76/faster_coco_eval/blob/main/examples/comparison/ultralytics/colab_example.ipynb example for ultralytics from faster_coco_eval repository
