### ISSUE TITLE
您好，请问GO-LSD部分具体的代码在哪里呀？

### ISSUE THREAD

**Issue by yaosx425** [Peterande/D-FINE#66]

**Comment by Peterande** [comment]
https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_criterion.py#L126-L176

相关的还有：
https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_utils.py#L43-L103

https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_utils.py#L132-L156

**Comment by yaosx425** [comment]
> https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_criterion.py#L126-L176
> 
> 相关的还有：
> 
> https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_utils.py#L43-L103
> 
> https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/src/zoo/dfine/dfine_utils.py#L132-L156

非常感谢！
