### ISSUE TITLE
Is D-FINE L model not transformer based?

### ISSUE THREAD

**Issue by AyushExel** [Peterande/D-FINE#67]
I see all other config files have transformer config parameters and hybrid config params as well, but not the L model (https://github.com/Peterande/D-FINE/blob/ee4a95199721e57300f0233f7c082506eb16ef05/configs/dfine/dfine_hgnetv2_l_coco.yml) . Is that correct?

**Comment by Peterande** [comment]
It inherits these default parameters from `configs/dfine/include/dfine_hgnetv2.yml`.
