### ISSUE TITLE
Question about detection in crowded scenes

### ISSUE THREAD

**Issue by chojinie** [Peterande/D-FINE#70]
Hello Author,
I greatly appreciate your excellent work.

I am working on a task where I need to detect people and obtain their bounding box information in images or videos containing over 50 individuals grouped together. I attempted to use your model and fine-tuned it on the CrowdHuman dataset. After performing inference using an intermediate checkpoint, I obtained the following results:

<img src="https://github.com/user-attachments/assets/eda61757-22b4-4c31-90d5-f37ba46556fb" alt="torch_results" width="300px">

<img src="https://github.com/user-attachments/assets/518b3c8f-9d26-4dc1-8c6e-67f4e599b8db" alt="ckpt_71" width="300px">

The left image shows the results using dfine_n_coco.pth, while the right image displays the results from the fine-tuned model.

As you can see, the model successfully detects only humans.

However, I noticed an issue in cases like the bottom left example, where multiple people are crowded together. Instead of detecting each individual separately, the model seems to mix individual detections with group detections, treating the entire group as a single "person" class.

I’m curious—does this represent an unsolved challenge in object detection tasks, or could you provide any hints or suggestions on how to address this issue?

Best regards,
Jin Cho

**Comment by Peterande** [comment]
I recommend not doing finetune on CrowdHuman and training from scratch. This dataset is too small and easy to overfit. In addition, for dense scenarios, if you want to detect more objects, you can appropriately lower the confidence threshold

**Comment by chojinie** [comment]
> I recommend not doing finetune on CrowdHuman and training from scratch. This dataset is too small and easy to overfit. In addition, for dense scenarios, if you want to detect more objects, you can appropriately lower the confidence threshold

Oh thanks i'll try. And i want to find confidence term in the code, but i can't. Where can i find that parameter?

**Comment by chojinie** [comment]
> > I recommend not doing finetune on CrowdHuman and training from scratch. This dataset is too small and easy to overfit. In addition, for dense scenarios, if you want to detect more objects, you can appropriately lower the confidence threshold
> 
> Oh thanks i'll try. And i want to find confidence term in the code, but i can't. Where can i find that parameter? I just have experience control threshold during inference on YOLO, but now i didn't see like that in the code.

Don't mind! I figured it out! Thank you for your guiding. I've training the model with CrowdHuman from scratch. And control the threshold when inference time. So i got a satisfying result.
