### ISSUE TITLE
Release D-FINE on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [Peterande/D-FINE#8]
Hello @Peterande 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work as it was trending on PapersWithCode and indexed the paper page here: https://huggingface.co/papers/2410.13842. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the checkpoints you've trained on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) we can provide you an A100 grant.

What do you think?

Kind regards,

Niels

**Comment by Peterande** [comment]
Dear Niels,
 
Thank you so much for reaching out! I'm really glad to hear about the great opportunities on Hugging Face. I'll work on it in the near future and follow the instructions you provided.
 
Best regards,
 
Yansong Peng

**Comment by NielsRogge** [comment]
Great :)

Also, in case you're interested in contributing D-FINE to the Transformers library, let me know!

We integrated models like [DETR](https://huggingface.co/docs/transformers/en/model_doc/detr), [Deformable DETR](https://huggingface.co/docs/transformers/en/model_doc/deformable_detr), [RT-DETR](https://huggingface.co/docs/transformers/main/en/model_doc/rt_detr) and more.

**Comment by Peterande** [comment]
I will look at some relevant cases and give it a try. Thank you～

**Comment by NielsRogge** [comment]
Thank you @Peterande, would it be possible to open this issue so that we can keep track of it?
