### ISSUE TITLE
Convert to onnx failed:

### ISSUE THREAD

**Issue by kkishore9891** [Peterande/D-FINE#83]
Hello, I trained a custom s model on my local gpu and I want to convert the best model into tensorrt. I tried to use the export_onnx.py program to do so and I am getting the following error:

```
python tools/deployment/export_onnx.py --check -c configs/dfine/custom/dfine_hgnetv2_s_custom.yml -r output/dfine_hgnetv2_s_custom/best_stg1.pth
/home/user/D-FINE/tools/deployment/export_onnx.py:28: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.resume, map_location='cpu')
Killed
```
 
 The program crashes at this particular block to be precise:

```
    torch.onnx.export(
        model,
        (data, size),
        output_file,
        input_names=['images', 'orig_target_sizes'],
        output_names=['labels', 'boxes', 'scores'],
        dynamic_axes=dynamic_axes,
        opset_version=16,
        verbose=False,
        do_constant_folding=True,
    )
```

Any help on how to fix this problem would be greatly appreciated. Thank you!

**Comment by archdsp** [comment]
This usually happens when `out of memory(OOM)`

You can check using below code.
```sh
dmesg | grep -E -i -B100 'killed process'
```

**Comment by kkishore9891** [comment]
Hello! Thank you for the response.
I tried to execute the script in a slightly more powerful computer and the issue didn't occur. Thank you for the support.

**Comment by pks916** [comment]
Please fix this, it takes too much CPU ram, even my 30gb kaggle instance couldn't handle the export and it crashes.

**Comment by olibartfast** [comment]
How much RAM do you need for export a S/M/L model?

**Comment by pks916** [comment]
i dont know it just keeps increasing and dumps

**Comment by olibartfast** [comment]
@kkishore9891 Which hardware specs did your computer have when the export succeeded? How much CPU and RAM were required?

**Comment by pks916** [comment]
on colab and kaggle free tier

**Comment by olibartfast** [comment]
Ok  fine, I found the reason, in [export onnx script](https://github.com/Peterande/D-FINE/blob/master/tools/deployment/export_onnx.py#L54) is hardcoded (something you never want in the real world D:) a batch size of 32, change based on your hardware RAM limit that your machine can handle

**Comment by pks916** [comment]
does it really increase memory usage that much just to accompany 32 images in batch instead of one
