### ISSUE TITLE
Make DFL possible in DETR?

### ISSUE THREAD

**Issue by ttjjmm** [Peterande/D-FINE#9]

**Comment by Peterande** [comment]
Sorry, I don't quite understand your question～
You can refer to https://github.com/Peterande/D-FINE/blob/4e8d80f7a241d06ebab052b47a03e720c0794de9/src/zoo/dfine/dfine_utils.py#L43 for more details

**Comment by ttjjmm** [comment]
I mean one of the motivations of this paper is to make "distribution focal loss" which is a regression method for bounding box optimization available in DETR platform.

**Comment by Peterande** [comment]
Originally, DFL couldn't be directly used to supervise the fine-grained distribution weighted by W(n). Firstly, we changed the way of obtaining the distribution ground truth and redefined the decoupled focal method to better adapt to DETR-like models and supervise the distribution more effectively. This is not entirely a motivation, but more like an optimization for FDR.
