### ISSUE TITLE
Error when load best_stg2.pth 

### ISSUE THREAD

**Issue by ai8049520** [Peterande/D-FINE#95]
Hello,

something wrong with my model when I try to load weights
I get:
RuntimeError: Error(s) in loading state_dict for DFINE:
	Missing key(s) in state_dict: "encoder.lateral_convs.0.conv_bn_fused.weight", ...

Before I successfully load trained in google colab model with same  configuration.
Training was successfully finished, but something wrong with model state_dict when I try to load it for inference test:
![image](https://github.com/user-attachments/assets/5c0e6fc3-9194-4d27-8a9b-6d8dea19cfac)

**Comment by ai8049520** [comment]
Found error in my config, case closed.

**Comment by FarhAnonymous** [comment]
Hey, I just trained my model and got my best_stg2.pth file but I cannot perform a basic detection on images that I trained on. Can you please help me out?? I know it's not very user friendly as YOLO but I tried my best but whenever I am running my file, it's throwing an error.
