### ISSUE TITLE
How can I add new augmentation?

### ISSUE THREAD

**Issue by ai8049520** [Peterande/D-FINE#97]
Can I add some additional transformation like that:
because I got error when I try?

train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0, p: 0.8}  # p = 0.5-> 0.8
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip, p: 0.5}
        - {type: ColorJitter, brightness: .5, contrast: 0.7, saturation: 0.4, hue: .3, p: 0.5}
        - {type: RandomInvert, p: 0.5}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72 # epoch in [71, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop', 'RandomHorizontalFlip', 'ColorJitter', 'RandomInvert']

**Comment by lz1004** [comment]
Hey there, you must also 
- add the new augmentations in the __init__.py in src/data/transforms and 
- register them in _transforms.py in src/data/transforms

**Comment by ai8049520** [comment]
Thank you. It works now!
